//! Typed Runtime client frames, identities, catalogs, routes, and conformance contracts.

mod agent_session;
mod catalog;
mod conformance;
mod frame;
mod identity;
pub mod protocol_identity;
mod protocol_validation;
mod routes;
mod schema_bundle;
mod server_method_catalog;
#[cfg(test)]
#[path = "../tests/unit/server_method_catalog.rs"]
mod server_method_catalog_tests;
mod session;
pub mod workspace_source_mutation;
pub use catalog::ClientCapabilities;
pub use catalog::ClientMethod;
pub use catalog::ClientParameter;
pub use catalog::ClientParameterCardinality;
pub use catalog::ClientParameterSource;
pub use catalog::ClientParameterType;
pub use catalog::ClientProtocolCatalog;
pub use catalog::ClientTransport;
pub use conformance::ClientAdmissionError;
pub use conformance::ClientConformanceCase;
pub use conformance::ClientConformanceReceipt;
pub use conformance::ClientConformanceSuite;
pub use frame::ClientFrame;
pub use frame::ClientFrameBase;
pub use frame::ClientInfo;
pub use frame::ClientOutcome;
pub use frame::TraceContext;
pub use identity::AgentChildThreadId;
pub use identity::AgentName;
pub use identity::AgentParentThreadId;
pub use identity::AgentPath;
pub use identity::AgentRootSessionId;
pub use identity::AgentRouteKey;
pub use identity::ClientProjectId;
pub use identity::ClientReasonKind;
pub use identity::ClientRequestId;
pub use identity::ClientRouteId;
pub use identity::ClientSchemaId;
pub use identity::ClientSessionId;
pub use identity::ClientWorkspaceIdentity;
pub use session::ClientSession;
pub use session::ClientSessionState;
#[cfg(test)]
#[path = "../tests/unit/workspace_source_mutation.rs"]
mod workspace_source_mutation_tests;
pub use routes::AspClientExactQueryFailure;
pub use routes::AspClientExactQueryRequest;
pub use routes::AspClientExactQueryResponse;
pub use routes::AspClientGraphsTimelineRequest;
pub use routes::AspClientRuntimeWorkCounters;
pub use routes::AspClientSearchPlaybookClauseAxis;
pub use routes::AspClientSearchPlaybookClauseRef;
pub use routes::AspClientSearchPlaybookGraphBlock;
pub use routes::AspClientSearchPlaybookSyntaxBlock;
pub use routes::AspClientSearchRequest;
pub use routes::AspClientSourceIndexLookupRequest;
pub use routes::AspClientWorkspaceSearchPlaybookRequest;
pub use routes::AspClientWorkspaceSyntaxQueryEvidence;
pub use routes::AspClientWorkspaceSyntaxQueryRequest;
pub use routes::AspClientWorkspaceSyntaxQueryResponse;
pub use routes::LIVE_CORPUS_CACHE_STATE_RECEIPT_SCHEMA_ID;
pub use routes::LIVE_CORPUS_CACHE_STATE_REQUEST_SCHEMA_ID;
pub use routes::LiveCorpusCacheStateReceipt;
pub use routes::LiveCorpusCacheStateRequest;
pub use routes::ProviderNativeExactProjection;
pub use routes::ProviderNativeExactRequest;
pub use routes::RuntimeProviderSearchRequest;
pub use schema_bundle::SCHEMA_BUNDLE_METHOD;
pub use schema_bundle::SCHEMA_BUNDLE_REQUEST_SCHEMA_ID;
pub use schema_bundle::SCHEMA_BUNDLE_RESPONSE_SCHEMA_ID;
pub use schema_bundle::SchemaBundleDocument;
pub use schema_bundle::SchemaBundleEntry;
pub use schema_bundle::SchemaBundleReceipt;
pub use schema_bundle::SchemaBundleRequest;
pub use schema_bundle::SchemaBundleResponse;
pub use server_method_catalog::CANCELLATION_PROBE_METHOD;
pub use server_method_catalog::CANCELLATION_PROBE_REQUEST_SCHEMA_ID;
pub use server_method_catalog::CANCELLATION_PROBE_RESPONSE_SCHEMA_ID;
pub use server_method_catalog::ClientDispatchClass;
pub use server_method_catalog::GRAPH_EVALUATE_METHOD;
pub use server_method_catalog::GRAPH_EVALUATE_REQUEST_SCHEMA_ID;
pub use server_method_catalog::GRAPH_EVALUATE_RESPONSE_SCHEMA_ID;
pub use server_method_catalog::GRAPH_TIMELINE_METHOD;
pub use server_method_catalog::GRAPH_TIMELINE_REQUEST_SCHEMA_ID;
pub use server_method_catalog::GRAPH_TIMELINE_RESPONSE_SCHEMA_ID;
pub use server_method_catalog::LIVE_CORPUS_CACHE_STATE_METHOD;
pub use server_method_catalog::MULTI_AGENT_CHILDREN_METHOD;
pub use server_method_catalog::MULTI_AGENT_HOST_EVENT_METHOD;
pub use server_method_catalog::ResolvedServerClientMethod;
pub use server_method_catalog::ServerClientRoute;
pub use server_method_catalog::WORKSPACE_GENERATION_ENSURE_READY_METHOD;
pub use server_method_catalog::WORKSPACE_GENERATION_ENSURE_READY_REQUEST_SCHEMA_ID;
pub use server_method_catalog::WORKSPACE_GENERATION_ENSURE_READY_RESPONSE_SCHEMA_ID;
pub use server_method_catalog::WORKSPACE_SEARCH_PLAYBOOK_METHOD;
pub use server_method_catalog::WORKSPACE_SYNTAX_QUERY_METHOD;
pub use server_method_catalog::classify_client_dispatch;
pub use server_method_catalog::resolve_server_client_method;
pub use server_method_catalog::resolve_server_client_method_owner;
pub use server_method_catalog::server_client_catalog;
pub use server_method_catalog::server_client_methods;

pub mod runtime_generation;

pub use protocol_validation::run_conformance_suite;

#[cfg(test)]
#[path = "../tests/unit/client_protocol_contract.rs"]
mod tests;
pub use agent_session::AGENT_SESSION_REGISTER_METHOD;
pub use agent_session::AGENT_SESSION_REGISTER_REQUEST_SCHEMA_ID;
pub use agent_session::AGENT_SESSION_REGISTER_RESPONSE_SCHEMA_ID;
pub use agent_session::AgentSessionPlatform;
pub use agent_session::AgentSessionRegisterReceipt;
pub use agent_session::AgentSessionRegisterRequest;
pub use agent_session::AgentSessionRegisterState;
pub use agent_session::AgentSessionRegistryOwner;
pub use agent_session::AgentSessionTransport;
