"""Command catalog for the Python tooling entrypoint."""

from __future__ import annotations

from .command_spec import CommandSpec


COMMANDS: tuple[CommandSpec, ...] = (
    CommandSpec(
        ("sandtable",),
        "tools.semantic_sandtable.cli",
        "semantic_sandtable_main",
        "argv",
        "Run semantic sandtable scenarios and receipt checks.",
    ),
    CommandSpec(
        ("parser", "compact-snapshots"),
        "tools.parser_compact_snapshots",
        "main",
        "argv",
        "Print the retired root compact snapshot migration notice.",
    ),
    CommandSpec(
        ("codeql", "bounded-evidence"),
        "tools.codeql_bounded_evidence",
        "emit_codeql_bounded_evidence",
        "argv",
        "Emit bounded CodeQL evidence metadata for ASP flow fixtures.",
    ),
    CommandSpec(
        ("codeql", "evidence"),
        "tools.codeql_evidence",
        "emit_codeql_evidence",
        "argv",
        "Emit CodeQL CLI metadata as ASP evidence.",
    ),
    CommandSpec(
        ("cache", "validate", "julia-performance"),
        "tools.julia_cache_performance",
        "main",
        "argv",
        "Validate Julia cache miss/hit performance evidence.",
    ),
    CommandSpec(
        ("graph", "turbo"),
        "asp_graph_turbo.cli",
        "main",
        "argv",
        "Rank typed ASP graph facts into compact frontier output.",
    ),
    CommandSpec(
        ("graph", "turbo", "artifacts"),
        "asp_graph_turbo.artifacts_cli",
        "main",
        "argv",
        "Evaluate graph turbo against cached ASP search artifacts.",
    ),
    CommandSpec(
        ("graph", "turbo", "timeline"),
        "asp_graph_turbo.timeline_cli",
        "main",
        "argv",
        "Infer search rounds and subagent microbursts from cached ASP artifacts.",
    ),
    CommandSpec(
        ("schema", "profiles"),
        "tools.schema_profiles",
        "main",
        "argv",
        "Validate language package schema downsync profiles.",
    ),
    CommandSpec(
        ("syntax", "real-evidence"),
        "tools.syntax_real_evidence",
        "main",
        "argv",
        "Render RFC 011 syntax real-project evidence records.",
    ),
    CommandSpec(
        ("tree-sitter", "contract"),
        "tools.tree_sitter.contract",
        "main",
        "legacy_argv",
        "Validate a grammar-profile contract fingerprint.",
    ),
    CommandSpec(
        ("tree-sitter", "validate", "json-abi-corpus"),
        "tools.tree_sitter.validate_json_abi_corpus",
        "main",
        "no_args",
        "Validate tree-sitter JSON ABI corpus capture output.",
    ),
    CommandSpec(
        ("tree-sitter", "validate", "contracts"),
        "tools.tree_sitter.contract_gates",
        "main",
        "argv",
        "Run the tree-sitter ABI rollout contract gates.",
    ),
    CommandSpec(
        ("tree-sitter", "validate", "runtime-boundary"),
        "tools.tree_sitter.contract_gates",
        "runtime_boundary_main",
        "argv",
        "Validate that language providers do not depend on tree-sitter runtime packages.",
    ),
    CommandSpec(
        ("tree-sitter", "validate", "frontier-code-contract"),
        "tools.tree_sitter.contract_gates",
        "frontier_code_main",
        "argv",
        "Validate tree-sitter locator/frontier and exact-code output.",
    ),
    CommandSpec(
        ("tree-sitter", "validate", "search-read-plan-frontier-contract"),
        "tools.tree_sitter.contract_gates",
        "search_read_plan_main",
        "argv",
        "Validate search/read-plan frontier output without inline code.",
    ),
    CommandSpec(
        ("tree-sitter", "validate", "exact-direct-read-contract"),
        "tools.tree_sitter.contract_gates",
        "exact_direct_read_main",
        "argv",
        "Validate exact direct-source-read frontier and pure-code output.",
    ),
    CommandSpec(
        ("tree-sitter", "validate", "python-query-corpus"),
        "tools.tree_sitter.validate_python_query_corpus",
        "main",
        "no_args",
        "Validate Python tree-sitter query corpus fixtures.",
    ),
    CommandSpec(
        ("tree-sitter", "validate", "rust-query-corpus"),
        "tools.tree_sitter.validate_rust_query_corpus",
        "main",
        "sys_argv",
        "Validate Rust tree-sitter query corpus fixtures.",
    ),
    CommandSpec(
        ("tree-sitter", "validate", "typescript-query-corpus"),
        "tools.tree_sitter.validate_typescript_query_corpus",
        "main",
        "sys_argv",
        "Validate TypeScript tree-sitter query corpus fixtures.",
    ),
    CommandSpec(
        ("tree-sitter", "sync", "query-snapshots"),
        "tools.tree_sitter.sync_query_snapshots",
        "main",
        "argv",
        "Sync tree-sitter query snapshots from an upstream checkout, excluding highlights.",
    ),
    CommandSpec(
        ("tree-sitter", "sync", "rust-queries"),
        "tools.tree_sitter.sync_rust_queries",
        "main",
        "sys_argv",
        "Sync Rust tree-sitter query snapshots from an upstream checkout.",
    ),
    CommandSpec(
        ("tree-sitter", "sync", "typescript-query-corpus"),
        "tools.tree_sitter.sync_typescript_query_corpus",
        "main",
        "sys_argv",
        "Refresh TypeScript tree-sitter query corpus metadata.",
    ),
    CommandSpec(
        ("validate", "language-workspace-search-contract"),
        "tools.language_workspace_search_contract",
        "main",
        "argv",
        "Validate cross-language workspace/search ingest provider contracts.",
    ),
    CommandSpec(
        ("validate", "provider-registry-contracts"),
        "tools.provider_registry_contracts",
        "main",
        "argv",
        "Validate real provider registry output against shared query contracts.",
    ),
)
