//! User-level Codex hook config rendering.

use std::path::Path;
use std::{fs, path::PathBuf};

use serde_json::{Value, json};
use sha2::{Digest, Sha256};

use crate::codex_config::{ALL_TOOL_ACTION_MATCHER, ROOT_BLOCK_BEGIN, ROOT_BLOCK_END};

const TRUST_BLOCK_BEGIN_PREFIX: &str = "# BEGIN agent-semantic-protocol trusted hook state: ";
const TRUST_BLOCK_END: &str = "# END agent-semantic-protocol trusted hook state";

#[derive(Debug)]
pub struct CodexGlobalHookTrustStatus {
    pub trust_config_path: PathBuf,
    pub trusted: bool,
    pub missing_events: Vec<String>,
    pub stale_events: Vec<String>,
}

#[derive(Debug, Clone, Copy)]
struct CodexGlobalHookEvent {
    config_name: &'static str,
    state_label: &'static str,
    matcher: Option<&'static str>,
    status: &'static str,
    hook_event: &'static str,
}

/// Render a user-level Codex hook block that dispatches through `asp hook`.
///
/// User-level hooks are project-neutral. The hook runtime resolves the current
/// workspace from Codex's working directory instead of hard-coding the project
/// that installed the hook.
pub fn codex_global_hook_block_with_binary(asp_binary: Option<&Path>) -> String {
    let body = codex_global_hook_events()
        .iter()
        .map(|event| codex_global_hook_event_block(event, asp_binary))
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "{ROOT_BLOCK_BEGIN}\n# Generated by `asp install plugin --codex`.\n# User-level dispatcher for activated semantic hook providers.\n\n{body}\n{ROOT_BLOCK_END}"
    )
}

/// Merge trust state for the user-level Codex hook block into Codex config.
pub fn merge_codex_global_hook_trust_config(
    existing: &str,
    config_source_path: &Path,
    asp_binary: Option<&Path>,
) -> String {
    let content = remove_codex_global_hook_trust_block(existing, config_source_path);
    let trust_block = codex_global_hook_trust_state_block(config_source_path, asp_binary);
    let prefix = content.trim_end();
    if prefix.is_empty() {
        format!("{trust_block}\n")
    } else {
        format!("{prefix}\n\n{trust_block}\n")
    }
}

pub fn remove_codex_global_hook_trust_config(existing: &str, config_source_path: &Path) -> String {
    let content = remove_codex_global_hook_trust_block(existing, config_source_path);
    if content.trim().is_empty() {
        String::new()
    } else {
        format!("{}\n", content.trim_end())
    }
}

pub fn codex_global_hook_config_present(content: &str) -> bool {
    if !content.contains(ROOT_BLOCK_BEGIN) || !content.contains(ROOT_BLOCK_END) {
        return false;
    }
    let Ok(parsed) = toml::from_str::<toml::Value>(content) else {
        return false;
    };
    let Some(hooks) = parsed.get("hooks").and_then(toml::Value::as_table) else {
        return false;
    };
    if hooks.contains_key("pre_tool_use") || hooks.contains_key("permission_request") {
        return false;
    }
    codex_global_hook_events().iter().all(|event| {
        let Some(groups) = hooks.get(event.config_name).and_then(toml::Value::as_array) else {
            return false;
        };
        if groups.len() != 1 {
            return false;
        }
        let group = &groups[0];
        if group.get("matcher").and_then(toml::Value::as_str) != event.matcher {
            return false;
        }
        let Some(commands) = group.get("hooks").and_then(toml::Value::as_array) else {
            return false;
        };
        commands.len() == 1
            && commands[0].get("type").and_then(toml::Value::as_str) == Some("command")
            && commands[0].get("timeout").and_then(toml::Value::as_integer) == Some(1)
    })
}

pub fn codex_global_hook_binary_path(content: &str) -> Option<PathBuf> {
    let parsed = toml::from_str::<toml::Value>(content).ok()?;
    let command = parsed
        .get("hooks")?
        .get("PreToolUse")?
        .as_array()?
        .first()?
        .get("hooks")?
        .as_array()?
        .first()?
        .get("command")?
        .as_str()?;
    let line = command
        .lines()
        .find(|line| line.trim_start().starts_with("exec "))?
        .trim_start()
        .strip_prefix("exec ")?;
    let binary = line.strip_suffix(" hook pre-tool --client codex")?.trim();
    let binary = binary
        .strip_prefix('\'')
        .and_then(|binary| binary.strip_suffix('\''))?;
    (!binary.is_empty() && !binary.contains("'\"'\"'")).then(|| PathBuf::from(binary))
}

pub fn codex_global_hook_trust_state_status(
    config_path: &Path,
) -> Result<CodexGlobalHookTrustStatus, String> {
    let content = fs::read_to_string(config_path)
        .map_err(|error| format!("failed to read {}: {error}", config_path.display()))?;
    let parsed = toml::from_str::<toml::Value>(&content)
        .map_err(|error| format!("invalid Codex config {}: {error}", config_path.display()))?;
    let asp_binary = codex_global_hook_binary_path(&content).ok_or_else(|| {
        format!(
            "global Codex Hook config {} omitted canonical ASP binary command",
            config_path.display()
        )
    })?;
    let state = parsed
        .get("hooks")
        .and_then(toml::Value::as_table)
        .and_then(|hooks| hooks.get("state"))
        .and_then(toml::Value::as_table);
    let mut missing_events = Vec::new();
    let mut stale_events = Vec::new();
    for event in codex_global_hook_events() {
        let key = format!("{}:{}:0:0", config_path.display(), event.state_label);
        let actual = state
            .and_then(|state| state.get(&key))
            .and_then(toml::Value::as_table)
            .and_then(|entry| entry.get("trusted_hash"))
            .and_then(toml::Value::as_str);
        let expected = codex_global_hook_trusted_hash(&event, Some(&asp_binary));
        match actual {
            None => missing_events.push(event.hook_event.to_owned()),
            Some(actual) if actual != expected => stale_events.push(event.hook_event.to_owned()),
            Some(_) => {}
        }
    }
    let trusted = codex_global_hook_config_present(&content)
        && missing_events.is_empty()
        && stale_events.is_empty();
    Ok(CodexGlobalHookTrustStatus {
        trust_config_path: config_path.to_path_buf(),
        trusted,
        missing_events,
        stale_events,
    })
}

fn codex_global_hook_events() -> [CodexGlobalHookEvent; 8] {
    [
        CodexGlobalHookEvent {
            config_name: "SessionStart",
            state_label: "session_start",
            matcher: Some("startup|resume|clear|compact"),
            status: "Loading semantic agent hook activation",
            hook_event: "session-start",
        },
        CodexGlobalHookEvent {
            config_name: "UserPromptSubmit",
            state_label: "user_prompt_submit",
            matcher: None,
            status: "Planning semantic search flow",
            hook_event: "user-prompt",
        },
        CodexGlobalHookEvent {
            config_name: "PreToolUse",
            state_label: "pre_tool_use",
            matcher: Some(ALL_TOOL_ACTION_MATCHER),
            status: "Checking semantic search flow",
            hook_event: "pre-tool",
        },
        CodexGlobalHookEvent {
            config_name: "PermissionRequest",
            state_label: "permission_request",
            matcher: Some(ALL_TOOL_ACTION_MATCHER),
            status: "Checking semantic approval flow",
            hook_event: "permission-request",
        },
        CodexGlobalHookEvent {
            config_name: "PostToolUse",
            state_label: "post_tool_use",
            matcher: None,
            status: "Updating semantic search flow state",
            hook_event: "post-tool",
        },
        CodexGlobalHookEvent {
            config_name: "SubagentStart",
            state_label: "subagent_start",
            matcher: Some(ALL_TOOL_ACTION_MATCHER),
            status: "Preparing semantic subagent context",
            hook_event: "subagent-start",
        },
        CodexGlobalHookEvent {
            config_name: "SubagentStop",
            state_label: "subagent_stop",
            matcher: Some(ALL_TOOL_ACTION_MATCHER),
            status: "Checking semantic subagent evidence",
            hook_event: "subagent-stop",
        },
        CodexGlobalHookEvent {
            config_name: "Stop",
            state_label: "stop",
            matcher: None,
            status: "Checking semantic changed files",
            hook_event: "stop",
        },
    ]
}

fn codex_global_hook_event_block(
    event: &CodexGlobalHookEvent,
    asp_binary: Option<&Path>,
) -> String {
    let matcher_line = event
        .matcher
        .map(|value| format!("matcher = {}\n\n", toml_basic_string(value)))
        .unwrap_or_else(|| "\n".to_string());
    let command = codex_global_hook_command(event.hook_event, asp_binary);
    format!(
        "[[hooks.{event_name}]]\n{matcher_line}[[hooks.{event_name}.hooks]]\ntype = \"command\"\ntimeout = 1\nstatusMessage = \"{status}\"\ncommand = '''\n{command}'''",
        event_name = event.config_name,
        status = event.status,
    )
}

fn codex_global_hook_command(hook_event: &str, asp_binary: Option<&Path>) -> String {
    let asp_binary = asp_binary
        .map(|path| shell_single_quoted(&path.display().to_string()))
        .unwrap_or_else(|| "asp".to_string());
    format!(
        "repo_root=\"${{CODEX_WORKSPACE_ROOT:-${{PWD:-.}}}}\"\ncd \"$repo_root\"\nexec {asp_binary} hook {hook_event} --client codex\n"
    )
}

fn codex_global_hook_trust_state_block(
    config_source_path: &Path,
    asp_binary: Option<&Path>,
) -> String {
    let state = codex_global_hook_events()
        .iter()
        .map(|event| codex_global_hook_state_block(config_source_path, event, asp_binary))
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "{}{}\n{state}\n{TRUST_BLOCK_END}",
        TRUST_BLOCK_BEGIN_PREFIX,
        config_source_path.display()
    )
}

fn codex_global_hook_state_block(
    config_source_path: &Path,
    event: &CodexGlobalHookEvent,
    asp_binary: Option<&Path>,
) -> String {
    let key = format!("{}:{}:0:0", config_source_path.display(), event.state_label);
    let hash = codex_global_hook_trusted_hash(event, asp_binary);
    format!(
        "[hooks.state.{}]\ntrusted_hash = {}",
        toml_basic_string(&key),
        toml_basic_string(&hash)
    )
}

fn codex_global_hook_trusted_hash(
    event: &CodexGlobalHookEvent,
    asp_binary: Option<&Path>,
) -> String {
    let mut identity = serde_json::Map::new();
    identity.insert(
        "event_name".to_string(),
        Value::String(event.state_label.to_string()),
    );
    if let Some(matcher) = event.matcher {
        identity.insert("matcher".to_string(), Value::String(matcher.to_string()));
    }
    identity.insert(
        "hooks".to_string(),
        Value::Array(vec![json!({
            "type": "command",
            "command": codex_global_hook_command(event.hook_event, asp_binary),
            "timeout": 1,
            "async": false,
            "statusMessage": event.status,
        })]),
    );
    version_for_codex_hook_identity(Value::Object(identity))
}

fn remove_codex_global_hook_trust_block(existing: &str, config_source_path: &Path) -> String {
    let begin = format!("{TRUST_BLOCK_BEGIN_PREFIX}{}", config_source_path.display());
    let state_table_prefix = format!("[hooks.state.\"{}:", config_source_path.display());
    let lines = existing.lines().collect::<Vec<_>>();
    let mut kept = Vec::new();
    let mut index = 0;
    let mut removed_state_table = false;
    while index < lines.len() {
        let trimmed = lines[index].trim();
        if trimmed == begin {
            index += 1;
            while index < lines.len() && lines[index].trim() != TRUST_BLOCK_END {
                index += 1;
            }
            if index < lines.len() {
                index += 1;
            }
            continue;
        }
        if trimmed.starts_with(&state_table_prefix) {
            removed_state_table = true;
            index += 1;
            while index < lines.len() {
                let next = lines[index].trim();
                if next.starts_with('[') || next.starts_with('#') {
                    break;
                }
                index += 1;
            }
            continue;
        }
        if removed_state_table && trimmed == TRUST_BLOCK_END {
            removed_state_table = false;
            index += 1;
            continue;
        }
        kept.push(lines[index]);
        index += 1;
    }
    kept.join("\n")
}

fn version_for_codex_hook_identity(value: Value) -> String {
    let canonical = canonical_json(value);
    let serialized = serde_json::to_vec(&canonical).unwrap_or_default();
    let hash = Sha256::digest(serialized);
    let hex = hash
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    format!("sha256:{hex}")
}

fn canonical_json(value: Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut keys = map.keys().cloned().collect::<Vec<_>>();
            keys.sort();
            let mut sorted = serde_json::Map::new();
            for key in keys {
                if let Some(value) = map.get(&key) {
                    sorted.insert(key, canonical_json(value.clone()));
                }
            }
            Value::Object(sorted)
        }
        Value::Array(items) => Value::Array(items.into_iter().map(canonical_json).collect()),
        other => other,
    }
}

fn toml_basic_string(value: &str) -> String {
    format!("{value:?}")
}

fn shell_single_quoted(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}
