//! User-level Codex hook config rendering.

use std::path::Path;

use serde_json::{Value, json};
use sha2::{Digest, Sha256};

use crate::codex_config::{ROOT_BLOCK_BEGIN, ROOT_BLOCK_END, codex_asp_explorer_role_block};

const TOOL_SURFACE_MATCHER: &str = r"Read|read|readFile|readDirectory|read_file|read_directory|FsReadFile|FsReadDirectory|fs\.read|fs\.readFile|fs\.readDirectory|fs/read|fs/readFile|fs/readDirectory|fs\\read|fs\\readFile|fs\\readDirectory|functions\.read|functions\.read_file|functions\.readFile|mcp__.*__read|mcp__.*__read_file|mcp__.*__readFile|functions\.exec_command|exec_command|command_execution|multi_tool_use\.parallel|Bash|Shell";
const TRUST_BLOCK_BEGIN_PREFIX: &str = "# BEGIN agent-semantic-protocol trusted hook state: ";
const TRUST_BLOCK_END: &str = "# END agent-semantic-protocol trusted hook state";

#[derive(Debug, Clone, Copy)]
struct CodexGlobalHookEvent {
    state_label: &'static str,
    matcher: Option<&'static str>,
    status: &'static str,
    hook_event: &'static str,
}

/// Render a user-level Codex hook block that dispatches through `asp hook`.
///
/// User-level hooks are project-neutral. The hook runtime resolves the current
/// workspace from Codex's working directory instead of hard-coding the project
/// that installed the hook.
pub fn codex_global_hook_block_with_binary(asp_binary: Option<&Path>) -> String {
    let body = codex_global_hook_events()
        .iter()
        .map(|event| codex_global_hook_event_block(event, asp_binary))
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "{ROOT_BLOCK_BEGIN}\n# Generated by `asp install plugin --codex`.\n# ASP Explorer role registration for Codex spawn_agent.\n\n{}\n\n# User-level dispatcher for activated semantic hook providers.\n\n{body}\n{ROOT_BLOCK_END}",
        codex_asp_explorer_role_block()
    )
}

/// Merge trust state for the user-level Codex hook block into Codex config.
pub fn merge_codex_global_hook_trust_config(
    existing: &str,
    config_source_path: &Path,
    asp_binary: Option<&Path>,
) -> String {
    let content = remove_codex_global_hook_trust_block(existing, config_source_path);
    let trust_block = codex_global_hook_trust_state_block(config_source_path, asp_binary);
    let prefix = content.trim_end();
    if prefix.is_empty() {
        format!("{trust_block}\n")
    } else {
        format!("{prefix}\n\n{trust_block}\n")
    }
}

fn codex_global_hook_events() -> [CodexGlobalHookEvent; 8] {
    [
        CodexGlobalHookEvent {
            state_label: "session_start",
            matcher: Some("startup|resume|clear|compact"),
            status: "Loading semantic agent hook activation",
            hook_event: "session-start",
        },
        CodexGlobalHookEvent {
            state_label: "user_prompt_submit",
            matcher: None,
            status: "Planning semantic search flow",
            hook_event: "user-prompt",
        },
        CodexGlobalHookEvent {
            state_label: "pre_tool_use",
            matcher: Some(TOOL_SURFACE_MATCHER),
            status: "Checking semantic search flow",
            hook_event: "pre-tool",
        },
        CodexGlobalHookEvent {
            state_label: "permission_request",
            matcher: Some(TOOL_SURFACE_MATCHER),
            status: "Checking semantic approval flow",
            hook_event: "permission-request",
        },
        CodexGlobalHookEvent {
            state_label: "post_tool_use",
            matcher: Some(TOOL_SURFACE_MATCHER),
            status: "Updating semantic search flow state",
            hook_event: "post-tool",
        },
        CodexGlobalHookEvent {
            state_label: "subagent_start",
            matcher: Some(TOOL_SURFACE_MATCHER),
            status: "Preparing semantic subagent context",
            hook_event: "subagent-start",
        },
        CodexGlobalHookEvent {
            state_label: "subagent_stop",
            matcher: Some(TOOL_SURFACE_MATCHER),
            status: "Checking semantic subagent evidence",
            hook_event: "subagent-stop",
        },
        CodexGlobalHookEvent {
            state_label: "stop",
            matcher: None,
            status: "Checking semantic changed files",
            hook_event: "stop",
        },
    ]
}

fn codex_global_hook_event_block(
    event: &CodexGlobalHookEvent,
    asp_binary: Option<&Path>,
) -> String {
    let matcher_line = event
        .matcher
        .map(|value| format!("matcher = {}\n\n", toml_basic_string(value)))
        .unwrap_or_else(|| "\n".to_string());
    let command = codex_global_hook_command(event.hook_event, asp_binary);
    format!(
        "[[hooks.{event_name}]]\n{matcher_line}[[hooks.{event_name}.hooks]]\ntype = \"command\"\ntimeout = 5\nstatusMessage = \"{status}\"\ncommand = '''\n{command}'''",
        event_name = event.state_label,
        status = event.status,
    )
}

fn codex_global_hook_command(hook_event: &str, asp_binary: Option<&Path>) -> String {
    let asp_binary = asp_binary
        .map(|path| shell_single_quoted(&path.display().to_string()))
        .unwrap_or_else(|| "asp".to_string());
    format!(
        "repo_root=\"${{CODEX_WORKSPACE_ROOT:-${{PWD:-.}}}}\"\ncd \"$repo_root\"\nexec direnv exec \"$repo_root\" {asp_binary} hook {hook_event} --client codex\n"
    )
}

fn codex_global_hook_trust_state_block(
    config_source_path: &Path,
    asp_binary: Option<&Path>,
) -> String {
    let state = codex_global_hook_events()
        .iter()
        .map(|event| codex_global_hook_state_block(config_source_path, event, asp_binary))
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "{}{}\n{state}\n{TRUST_BLOCK_END}",
        TRUST_BLOCK_BEGIN_PREFIX,
        config_source_path.display()
    )
}

fn codex_global_hook_state_block(
    config_source_path: &Path,
    event: &CodexGlobalHookEvent,
    asp_binary: Option<&Path>,
) -> String {
    let key = format!("{}:{}:0:0", config_source_path.display(), event.state_label);
    let hash = codex_global_hook_trusted_hash(event, asp_binary);
    format!(
        "[hooks.state.{}]\ntrusted_hash = {}",
        toml_basic_string(&key),
        toml_basic_string(&hash)
    )
}

fn codex_global_hook_trusted_hash(
    event: &CodexGlobalHookEvent,
    asp_binary: Option<&Path>,
) -> String {
    let mut identity = serde_json::Map::new();
    identity.insert(
        "event_name".to_string(),
        Value::String(event.state_label.to_string()),
    );
    if let Some(matcher) = event.matcher {
        identity.insert("matcher".to_string(), Value::String(matcher.to_string()));
    }
    identity.insert(
        "hooks".to_string(),
        Value::Array(vec![json!({
            "type": "command",
            "command": codex_global_hook_command(event.hook_event, asp_binary),
            "timeout": 5,
            "async": false,
            "statusMessage": event.status,
        })]),
    );
    version_for_codex_hook_identity(Value::Object(identity))
}

fn remove_codex_global_hook_trust_block(existing: &str, config_source_path: &Path) -> String {
    let begin = format!("{TRUST_BLOCK_BEGIN_PREFIX}{}", config_source_path.display());
    let lines = existing.lines().collect::<Vec<_>>();
    let mut kept = Vec::new();
    let mut index = 0;
    while index < lines.len() {
        if lines[index].trim() == begin {
            index += 1;
            while index < lines.len() && lines[index].trim() != TRUST_BLOCK_END {
                index += 1;
            }
            if index < lines.len() {
                index += 1;
            }
            continue;
        }
        kept.push(lines[index]);
        index += 1;
    }
    kept.join("\n")
}

fn version_for_codex_hook_identity(value: Value) -> String {
    let canonical = canonical_json(value);
    let serialized = serde_json::to_vec(&canonical).unwrap_or_default();
    let hash = Sha256::digest(serialized);
    let hex = hash
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    format!("sha256:{hex}")
}

fn canonical_json(value: Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut keys = map.keys().cloned().collect::<Vec<_>>();
            keys.sort();
            let mut sorted = serde_json::Map::new();
            for key in keys {
                if let Some(value) = map.get(&key) {
                    sorted.insert(key, canonical_json(value.clone()));
                }
            }
            Value::Object(sorted)
        }
        Value::Array(items) => Value::Array(items.into_iter().map(canonical_json).collect()),
        other => other,
    }
}

fn toml_basic_string(value: &str) -> String {
    format!("{value:?}")
}

fn shell_single_quoted(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}
