//! Client project config install helpers for asp hook.

use crate::codex_trust::{
    TRUST_BLOCK_END, codex_project_trusted, codex_trust_block_begin,
    merge_codex_project_trust_config, merge_codex_trust_config, toml_basic_string,
};
use agent_semantic_runtime::project_activation_path;
use serde_json::{Map, Value, json};
use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Start marker for the managed project-level Codex hook block.
pub const ROOT_BLOCK_BEGIN: &str = "# BEGIN agent-semantic-protocol agent hooks";
/// End marker for the managed project-level Codex hook block.
pub const ROOT_BLOCK_END: &str = "# END agent-semantic-protocol agent hooks";

const TOOL_SURFACE_MATCHER: &str = r"Read|read|readFile|readDirectory|read_file|read_directory|FsReadFile|FsReadDirectory|fs\.read|fs\.readFile|fs\.readDirectory|fs/read|fs/readFile|fs/readDirectory|fs\\read|fs\\readFile|fs\\readDirectory|functions\.read|functions\.read_file|functions\.readFile|mcp__.*__read|mcp__.*__read_file|mcp__.*__readFile|functions\.exec_command|exec_command|command_execution|multi_tool_use\.parallel|Bash|Shell";
const ASP_EXPLORER_ROLE_NAME: &str = "asp_explorer";
const ASP_EXPLORER_CONFIG_FILE: &str = "agents/asp-explorer.toml";
const ASP_EXPLORER_DESCRIPTION: &str = "ASP search/query evidence explorer.";

#[derive(Debug)]
/// Status of the Codex user trust entries required for project hooks.
pub struct CodexUserTrustStatus {
    /// User-level Codex config containing hook trust hashes.
    pub trust_config_path: PathBuf,
    /// Whether Codex can load this project's local config and all hook events are trusted.
    pub trusted: bool,
    /// Whether the user-level Codex config trusts this project root.
    pub project_trusted: bool,
    /// Whether all required hook event hashes match the current project config.
    pub hook_state_trusted: bool,
    /// Hook event names still missing trusted state.
    pub missing_events: Vec<String>,
    /// Hook event names with trusted state that no longer matches the current hook block.
    pub stale_events: Vec<String>,
}

#[derive(Debug, Clone, Copy)]
struct CodexHookEvent {
    event: &'static str,
    state_label: &'static str,
    matcher: Option<&'static str>,
    status: &'static str,
    hook_event: &'static str,
}

const CLAUDE_MANAGED_COMMAND_MARKER: &str = "# Generated by asp install hook --client claude.";

struct ClaudeHookEvent {
    event: &'static str,
    matcher: Option<&'static str>,
    hook_event: &'static str,
}

/// Render the managed Codex hook block that dispatches through `asp hook`.
pub fn codex_hook_block(project_root: &Path) -> String {
    let events = codex_hook_events();
    let body = events
        .iter()
        .map(|event| codex_hook_event_block(event, project_root))
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "{ROOT_BLOCK_BEGIN}\n# Generated by `asp install plugin --codex`.\n# ASP Explorer role registration for Codex spawn_agent.\n\n{}\n\n# Root dispatcher for activated semantic hook providers.\n\n{body}\n{ROOT_BLOCK_END}",
        codex_asp_explorer_role_block()
    )
}

pub fn codex_asp_explorer_role_block() -> String {
    format!(
        "[agents.{ASP_EXPLORER_ROLE_NAME}]\ndescription = {}\nconfig_file = {}\nnickname_candidates = [\"ASP Explore\", \"ASP Reasoning\", \"ASP Search\"]",
        toml_basic_string(ASP_EXPLORER_DESCRIPTION),
        toml_basic_string(ASP_EXPLORER_CONFIG_FILE),
    )
}

/// Merge the Codex ASP Explorer role registration into project config text.
///
/// Plugin-based installs keep hook registration in the plugin, but Codex still
/// needs this role entry to expose the read-only ASP custom agent.
pub fn merge_codex_asp_explorer_role_config(existing: &str) -> Result<String, String> {
    validate_codex_config_toml(existing)?;
    let parsed = toml::from_str::<toml::Value>(existing)
        .map_err(|error| format!("invalid Codex config TOML: {error}"))?;
    let has_role = parsed
        .get("agents")
        .and_then(toml::Value::as_table)
        .and_then(|agents| agents.get(ASP_EXPLORER_ROLE_NAME))
        .is_some();
    let prefix = existing.trim_end();
    if has_role {
        return Ok(if prefix.is_empty() {
            String::new()
        } else {
            format!("{prefix}\n")
        });
    }
    let role_block = codex_asp_explorer_role_block();
    Ok(if prefix.is_empty() {
        format!("{role_block}\n")
    } else {
        format!("{prefix}\n\n{role_block}\n")
    })
}

/// Install user-level Codex trust state for the managed project hook block.
pub fn install_codex_user_trust_state(project_config_path: &Path) -> Result<PathBuf, String> {
    let project_config_path = fs::canonicalize(project_config_path).map_err(|error| {
        format!(
            "failed to resolve project Codex config {}: {error}",
            project_config_path.display()
        )
    })?;
    let project_root = project_root_for_codex_config_path(&project_config_path)?;
    let codex_home = codex_home_path()?;
    fs::create_dir_all(&codex_home)
        .map_err(|error| format!("failed to create {}: {error}", codex_home.display()))?;
    let user_config_path = codex_home.join("config.toml");
    let existing = fs::read_to_string(&user_config_path).unwrap_or_default();
    if user_config_path.is_file() {
        validate_codex_config_toml(&existing).map_err(|error| {
            format!(
                "refusing to write invalid Codex user config {}: {error}",
                user_config_path.display()
            )
        })?;
    }
    let trust_block = codex_trust_state_block(&project_config_path, &project_root);
    let merged = merge_codex_project_trust_config(&existing, &project_root)?;
    let merged = merge_codex_trust_config(&merged, &project_config_path, &trust_block);
    validate_codex_config_toml(&merged).map_err(|error| {
        format!(
            "refusing to write invalid Codex user trust config {}: {error}",
            user_config_path.display()
        )
    })?;
    fs::write(&user_config_path, merged.as_bytes())
        .map_err(|error| format!("failed to write {}: {error}", user_config_path.display()))?;
    Ok(user_config_path)
}

/// Inspect user-level Codex trust state for a project hook config.
pub fn codex_user_trust_state_status(
    project_config_path: &Path,
) -> Result<CodexUserTrustStatus, String> {
    let project_config_path = fs::canonicalize(project_config_path).map_err(|error| {
        format!(
            "failed to resolve project Codex config {}: {error}",
            project_config_path.display()
        )
    })?;
    let project_root = project_root_for_codex_config_path(&project_config_path)?;
    let trust_config_path = codex_home_path()?.join("config.toml");
    let content = fs::read_to_string(&trust_config_path).unwrap_or_default();
    let parsed =
        toml::from_str::<toml::Value>(&content)
            .unwrap_or(toml::Value::Table(
                toml::map::Map::<String, toml::Value>::new(),
            ));
    let state = parsed
        .get("hooks")
        .and_then(toml::Value::as_table)
        .and_then(|hooks| hooks.get("state"))
        .and_then(toml::Value::as_table);
    let mut missing_events = Vec::new();
    let mut stale_events = Vec::new();
    for event in codex_hook_events() {
        let expected_hash = codex_hook_trusted_hash(&event, &project_root);
        match codex_hook_trust_hash(state, &project_config_path, &event) {
            Some(actual_hash) if actual_hash == expected_hash => {}
            Some(_) => stale_events.push(event.hook_event.to_string()),
            None => missing_events.push(event.hook_event.to_string()),
        }
    }
    let project_trusted = codex_project_trusted(&parsed, &project_root);
    let hook_state_trusted = missing_events.is_empty() && stale_events.is_empty();
    Ok(CodexUserTrustStatus {
        trust_config_path,
        trusted: project_trusted && hook_state_trusted,
        project_trusted,
        hook_state_trusted,
        missing_events,
        stale_events,
    })
}

fn codex_hook_trust_hash(
    state: Option<&toml::map::Map<String, toml::Value>>,
    project_config_path: &Path,
    event: &CodexHookEvent,
) -> Option<String> {
    let key = format!(
        "{}:{}:0:0",
        project_config_path.display(),
        event.state_label
    );
    state
        .and_then(|state| state.get(&key))
        .and_then(toml::Value::as_table)
        .and_then(|entry| entry.get("trusted_hash"))
        .and_then(toml::Value::as_str)
        .map(str::to_string)
}

/// Validate Codex config text as TOML before writing it back to disk.
pub fn validate_codex_config_toml(content: &str) -> Result<(), String> {
    toml::from_str::<toml::Value>(content)
        .map(|_| ())
        .map_err(|error| error.to_string())
}

/// Merge the managed hook block into existing Codex project config text.
pub fn merge_codex_config(existing: &str, block: &str) -> String {
    let mut content = remove_managed_block(existing, ROOT_BLOCK_BEGIN, ROOT_BLOCK_END);
    content = ensure_codex_required_features(&content);
    let prefix = content.trim();
    if prefix.is_empty() {
        format!(
            "[features]\nhooks = true\nunified_exec = true\n\n{}\n",
            block.trim_end()
        )
    } else {
        format!("{}\n\n{}\n", prefix, block.trim_end())
    }
}

fn codex_hook_events() -> [CodexHookEvent; 8] {
    [
        CodexHookEvent {
            event: "SessionStart",
            state_label: "session_start",
            matcher: Some("startup|resume|clear|compact"),
            status: "Loading semantic agent hook activation",
            hook_event: "session-start",
        },
        CodexHookEvent {
            event: "UserPromptSubmit",
            state_label: "user_prompt_submit",
            matcher: None,
            status: "Planning semantic search flow",
            hook_event: "user-prompt",
        },
        CodexHookEvent {
            event: "PreToolUse",
            state_label: "pre_tool_use",
            matcher: Some(TOOL_SURFACE_MATCHER),
            status: "Checking semantic search flow",
            hook_event: "pre-tool",
        },
        CodexHookEvent {
            event: "PermissionRequest",
            state_label: "permission_request",
            matcher: Some(TOOL_SURFACE_MATCHER),
            status: "Checking semantic approval flow",
            hook_event: "permission-request",
        },
        CodexHookEvent {
            event: "PostToolUse",
            state_label: "post_tool_use",
            matcher: Some(TOOL_SURFACE_MATCHER),
            status: "Updating semantic search flow state",
            hook_event: "post-tool",
        },
        CodexHookEvent {
            event: "SubagentStart",
            state_label: "subagent_start",
            matcher: Some(TOOL_SURFACE_MATCHER),
            status: "Preparing semantic subagent context",
            hook_event: "subagent-start",
        },
        CodexHookEvent {
            event: "SubagentStop",
            state_label: "subagent_stop",
            matcher: Some(TOOL_SURFACE_MATCHER),
            status: "Checking semantic subagent evidence",
            hook_event: "subagent-stop",
        },
        CodexHookEvent {
            event: "Stop",
            state_label: "stop",
            matcher: None,
            status: "Checking semantic changed files",
            hook_event: "stop",
        },
    ]
}

fn codex_hook_event_block(event: &CodexHookEvent, project_root: &Path) -> String {
    let matcher_line = event
        .matcher
        .map(|value| format!("matcher = {}\n\n", toml_basic_string(value)))
        .unwrap_or_else(|| "\n".to_string());
    let command = codex_hook_command(event.hook_event, project_root);
    format!(
        "[[hooks.{event_name}]]\n{matcher_line}[[hooks.{event_name}.hooks]]\ntype = \"command\"\ntimeout = 5\nstatusMessage = \"{status}\"\ncommand = '''\n{command}'''",
        event_name = event.event,
        status = event.status,
    )
}

fn codex_hook_command(hook_event: &str, project_root: &Path) -> String {
    let activation_path = project_activation_path(project_root)
        .expect("State Core activation path should resolve for Codex hook config");
    let project_root = shell_single_quoted(&project_root.display().to_string());
    let activation_path = shell_single_quoted(&activation_path.display().to_string());
    format!(
        "repo_root={project_root}\ncd \"$repo_root\"\nactivation={activation_path}\nexec direnv exec \"$repo_root\" \"$repo_root/.bin/asp\" hook {hook_event} --client codex --activation \"$activation\"\n"
    )
}

fn codex_hook_state_block(
    config_source_path: &Path,
    event: &CodexHookEvent,
    project_root: &Path,
) -> String {
    let key = format!("{}:{}:0:0", config_source_path.display(), event.state_label);
    let hash = codex_hook_trusted_hash(event, project_root);
    format!(
        "[hooks.state.{}]\ntrusted_hash = {}",
        toml_basic_string(&key),
        toml_basic_string(&hash)
    )
}

fn codex_home_path() -> Result<PathBuf, String> {
    if let Some(path) = env::var_os("CODEX_HOME").filter(|value| !value.is_empty()) {
        return Ok(PathBuf::from(path));
    }
    env::var_os("HOME")
        .filter(|value| !value.is_empty())
        .map(|home| PathBuf::from(home).join(".codex"))
        .ok_or_else(|| {
            "missing CODEX_HOME and HOME; cannot write Codex hook trust state".to_string()
        })
}

fn codex_trust_state_block(config_source_path: &Path, project_root: &Path) -> String {
    let state = codex_hook_events()
        .iter()
        .map(|event| codex_hook_state_block(config_source_path, event, project_root))
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "{}\n{state}\n{TRUST_BLOCK_END}",
        codex_trust_block_begin(config_source_path)
    )
}

fn codex_hook_trusted_hash(event: &CodexHookEvent, project_root: &Path) -> String {
    let mut identity = serde_json::Map::new();
    identity.insert(
        "event_name".to_string(),
        Value::String(event.state_label.to_string()),
    );
    if let Some(matcher) = event.matcher {
        identity.insert("matcher".to_string(), Value::String(matcher.to_string()));
    }
    identity.insert(
        "hooks".to_string(),
        Value::Array(vec![json!({
            "type": "command",
            "command": codex_hook_command(event.hook_event, project_root),
            "timeout": 5,
            "async": false,
            "statusMessage": event.status,
        })]),
    );
    version_for_codex_hook_identity(Value::Object(identity))
}

fn version_for_codex_hook_identity(value: Value) -> String {
    let canonical = canonical_json(value);
    let serialized = serde_json::to_vec(&canonical).unwrap_or_default();
    let hash = Sha256::digest(serialized);
    let hex = hash
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    format!("sha256:{hex}")
}

/// Return the versioned Claude project settings path.
pub fn default_claude_settings_path(project_root: &str) -> PathBuf {
    PathBuf::from(project_root)
        .join(".claude")
        .join("settings.json")
}

/// Render the managed Claude hook settings fragment.
pub fn claude_hook_block(project_root: &Path) -> Value {
    let mut hooks = Map::new();
    for event in claude_hook_events() {
        hooks.insert(
            event.event.to_string(),
            Value::Array(vec![claude_hook_event_group(&event, project_root)]),
        );
    }
    json!({ "hooks": hooks })
}

/// Validate Claude settings JSON before writing a merged config.
pub fn validate_claude_settings_json(settings: &str) -> Result<(), String> {
    if settings.trim().is_empty() {
        return Ok(());
    }
    serde_json::from_str::<Value>(settings)
        .map(|_| ())
        .map_err(|error| error.to_string())
}

/// Merge the managed Claude hook block into existing project settings JSON.
pub fn merge_claude_settings(existing: &str, block: &Value) -> Result<String, String> {
    let mut root = if existing.trim().is_empty() {
        Value::Object(Map::new())
    } else {
        serde_json::from_str(existing).map_err(|error| error.to_string())?
    };
    let root_object = root
        .as_object_mut()
        .ok_or_else(|| "Claude settings JSON must be an object".to_string())?;
    let hooks = root_object
        .entry("hooks")
        .or_insert_with(|| Value::Object(Map::new()));
    let hooks_object = hooks
        .as_object_mut()
        .ok_or_else(|| "Claude settings hooks must be an object".to_string())?;
    let block_hooks = block
        .get("hooks")
        .and_then(Value::as_object)
        .ok_or_else(|| "managed Claude hook block must contain hooks object".to_string())?;
    let existing_event_names = hooks_object.keys().cloned().collect::<Vec<_>>();
    for event_name in existing_event_names {
        let Some(groups) = hooks_object
            .get_mut(&event_name)
            .and_then(Value::as_array_mut)
        else {
            continue;
        };
        groups.retain(|group| !is_managed_claude_group(group));
    }
    hooks_object.retain(|_, groups| groups.as_array().is_none_or(|groups| !groups.is_empty()));
    for (event_name, managed_groups) in block_hooks {
        let groups = hooks_object
            .entry(event_name.clone())
            .or_insert_with(|| Value::Array(Vec::new()));
        let groups = groups
            .as_array_mut()
            .ok_or_else(|| format!("Claude settings hooks.{event_name} must be an array"))?;
        let Some(managed_groups) = managed_groups.as_array() else {
            return Err(format!(
                "managed Claude hook block hooks.{event_name} must be an array"
            ));
        };
        groups.extend(managed_groups.iter().cloned());
    }
    serde_json::to_string_pretty(&root)
        .map(|settings| format!("{settings}\n"))
        .map_err(|error| error.to_string())
}

fn claude_hook_events() -> [ClaudeHookEvent; 7] {
    [
        ClaudeHookEvent {
            event: "SessionStart",
            matcher: None,
            hook_event: "session-start",
        },
        ClaudeHookEvent {
            event: "UserPromptSubmit",
            matcher: None,
            hook_event: "user-prompt",
        },
        ClaudeHookEvent {
            event: "PreToolUse",
            matcher: Some(TOOL_SURFACE_MATCHER),
            hook_event: "pre-tool",
        },
        ClaudeHookEvent {
            event: "PostToolUse",
            matcher: Some(TOOL_SURFACE_MATCHER),
            hook_event: "post-tool",
        },
        ClaudeHookEvent {
            event: "SubagentStart",
            matcher: None,
            hook_event: "subagent-start",
        },
        ClaudeHookEvent {
            event: "SubagentStop",
            matcher: None,
            hook_event: "subagent-stop",
        },
        ClaudeHookEvent {
            event: "Stop",
            matcher: None,
            hook_event: "stop",
        },
    ]
}

fn claude_hook_event_group(event: &ClaudeHookEvent, project_root: &Path) -> Value {
    let mut group = Map::new();
    if let Some(matcher) = event.matcher {
        group.insert("matcher".to_string(), Value::String(matcher.to_string()));
    }
    group.insert(
        "hooks".to_string(),
        Value::Array(vec![json!({
            "type": "command",
            "timeout": 5,
            "command": claude_hook_command(event.hook_event, project_root),
        })]),
    );
    Value::Object(group)
}

fn claude_hook_command(hook_event: &str, project_root: &Path) -> String {
    let activation_path = project_activation_path(project_root)
        .expect("State Core activation path should resolve for Claude hook config");
    let project_root = shell_single_quoted(&project_root.display().to_string());
    let activation_path = shell_single_quoted(&activation_path.display().to_string());
    format!(
        "{CLAUDE_MANAGED_COMMAND_MARKER}\nrepo_root={project_root}\ncd \"$repo_root\"\nactivation={activation_path}\nexec asp hook {hook_event} --client claude --activation \"$activation\"\n"
    )
}

fn project_root_for_codex_config_path(project_config_path: &Path) -> Result<PathBuf, String> {
    let codex_dir = project_config_path
        .parent()
        .ok_or_else(|| "Codex config path has no parent directory".to_string())?;
    if codex_dir.file_name().and_then(|value| value.to_str()) != Some(".codex") {
        return Err(format!(
            "Codex config path {} is not under a .codex directory",
            project_config_path.display()
        ));
    }
    codex_dir
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| "Codex config path has no project root".to_string())
}

fn shell_single_quoted(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn is_managed_claude_group(group: &Value) -> bool {
    group
        .get("hooks")
        .and_then(Value::as_array)
        .is_some_and(|hooks| hooks.iter().any(is_managed_claude_hook))
}

fn is_managed_claude_hook(hook: &Value) -> bool {
    hook.get("command")
        .and_then(Value::as_str)
        .is_some_and(|command| {
            command.contains(CLAUDE_MANAGED_COMMAND_MARKER)
                || (command.contains("asp hook") && command.contains("--client claude"))
        })
}

fn canonical_json(value: Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut keys = map.keys().cloned().collect::<Vec<_>>();
            keys.sort();
            let mut sorted = serde_json::Map::new();
            for key in keys {
                if let Some(value) = map.get(&key) {
                    sorted.insert(key, canonical_json(value.clone()));
                }
            }
            Value::Object(sorted)
        }
        Value::Array(items) => Value::Array(items.into_iter().map(canonical_json).collect()),
        other => other,
    }
}

fn ensure_codex_required_features(existing: &str) -> String {
    let mut table = String::new();
    let mut lines = existing
        .lines()
        .filter_map(|line| {
            let trimmed = line.trim();
            let skip = is_top_level_codex_feature(&table, trimmed);
            if let Some(header) = toml_table_header(trimmed) {
                table = header;
            }
            (!skip).then(|| line.to_string())
        })
        .collect::<Vec<_>>();

    let Some(features_start) = lines
        .iter()
        .position(|line| toml_table_header(line.trim()).as_deref() == Some("features"))
    else {
        let body = lines.join("\n").trim().to_string();
        return if body.is_empty() {
            "[features]\nhooks = true\nunified_exec = true".to_string()
        } else {
            format!("[features]\nhooks = true\nunified_exec = true\n\n{body}")
        };
    };

    let mut features_end = lines
        .iter()
        .enumerate()
        .skip(features_start + 1)
        .find_map(|(index, line)| toml_table_header(line.trim()).map(|_| index))
        .unwrap_or(lines.len());

    for key in ["hooks", "unified_exec"] {
        ensure_codex_feature_key(&mut lines, features_start, &mut features_end, key);
    }
    lines.join("\n")
}

fn ensure_codex_feature_key(
    lines: &mut Vec<String>,
    features_start: usize,
    features_end: &mut usize,
    key: &str,
) {
    if let Some(index) = lines[features_start + 1..*features_end]
        .iter()
        .position(|line| is_codex_feature_key(line.trim(), key))
        .map(|relative_index| features_start + 1 + relative_index)
    {
        lines[index] = format!("{key} = true");
    } else {
        lines.insert(*features_end, format!("{key} = true"));
        *features_end += 1;
    }
}

fn is_top_level_codex_feature(table: &str, trimmed: &str) -> bool {
    table.is_empty()
        && ["hooks", "unified_exec"]
            .iter()
            .any(|key| is_codex_feature_key(trimmed, key))
}

fn is_codex_feature_key(trimmed: &str, key: &str) -> bool {
    if trimmed.is_empty() || trimmed.starts_with('#') {
        return false;
    }
    trimmed
        .split_once('=')
        .is_some_and(|(candidate, _)| candidate.trim() == key)
}

fn toml_table_header(trimmed: &str) -> Option<String> {
    if !trimmed.starts_with('[') || !trimmed.ends_with(']') {
        return None;
    }
    let header = trimmed.trim_matches(['[', ']']).trim();
    (!header.is_empty()).then(|| header.to_string())
}

fn remove_managed_block(existing: &str, begin: &str, end: &str) -> String {
    let mut content = existing.to_string();
    while let Some(start) = content.find(begin) {
        let Some(end_marker_start) = content[start..].find(end) else {
            break;
        };
        let end_index = start + end_marker_start + end.len();
        content.replace_range(start..end_index, "");
    }
    content.trim().to_string()
}
