//! Activation schema DTOs and resolved runtime provider routing.

use globset::{GlobBuilder, GlobSet, GlobSetBuilder};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::protocol::{
    AgentHookError, CommandTemplate, DecisionRoute, DecisionRouteKind, HOOK_ACTIVATION_SCHEMA_ID,
    HOOK_ACTIVATION_SCHEMA_VERSION, HOOK_PROTOCOL_ID, HOOK_PROTOCOL_VERSION, HookPolicy,
    HookRoutes, PROVIDER_MANIFEST_SCHEMA_ID, PROVIDER_MANIFEST_SCHEMA_VERSION,
    normalize_source_selector,
};

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
/// Repository-local activation generated by `asp install hook`.
pub struct HookActivation {
    pub schema_id: String,
    pub schema_version: String,
    pub protocol_id: String,
    pub protocol_version: String,
    pub project_root: String,
    pub generated_by: ActivationGeneratedBy,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<String>,
    pub providers: Vec<ActivatedProviderConfig>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
/// Runtime and version that generated a project activation.
pub struct ActivationGeneratedBy {
    pub runtime: String,
    pub version: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
/// Repository-local provider activation without provider routes or policies.
///
/// Raw DTO boundary: serialized hook activation keeps primitive transport
/// fields that `resolve_activation` validates against provider manifests.
pub struct ActivatedProviderConfig {
    pub manifest_id: String,
    pub manifest_digest: String,
    pub language_id: String,
    pub provider_id: String,
    pub binary: String,
    #[serde(default)]
    pub execution: ProviderExecution,
    #[serde(default)]
    pub provider_command_prefix: Vec<String>,
    #[serde(default)]
    pub search_capabilities: serde_json::Value,
    pub coverage: ActivationCoverage,
}

/// Execution mode used to invoke a provider from ASP.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ProviderExecution {
    /// Provider is executed as an external process.
    #[default]
    ExternalProcess,
    /// Provider is linked into the ASP runtime and dispatched in-process.
    Embedded,
}

impl ProviderExecution {
    /// Stable line-protocol label for provider diagnostics.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::ExternalProcess => "external-process",
            Self::Embedded => "embedded",
        }
    }
}

/// Coverage defaults activated from a provider manifest for hook routing.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ActivationCoverage {
    pub package_roots: Vec<String>,
    pub source_roots: Vec<String>,
    pub config_files: Vec<String>,
    pub source_extensions: Vec<String>,
    pub ignored_path_prefixes: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
/// Static provider-owned hook manifest.
///
/// Raw DTO boundary: provider manifest JSON keeps primitive transport fields
/// that `parse_activation` validates before runtime routing.
pub struct ProviderManifest {
    pub schema_id: String,
    pub schema_version: String,
    pub protocol_id: String,
    pub protocol_version: String,
    pub manifest_id: String,
    pub manifest_version: String,
    pub language_id: String,
    pub provider_id: String,
    pub namespace: String,
    pub binary: String,
    #[serde(default)]
    pub execution: ProviderExecution,
    pub source: ManifestSourceDefaults,
    #[serde(default)]
    pub search_capabilities: ProviderSearchCapabilities,
    pub policy: HookPolicy,
    pub routes: HookRoutes,
}

/// Provider-owned search surfaces that ASP may delegate instead of approximating.
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderSearchCapabilities {
    #[serde(default)]
    pub owner_items: bool,
    #[serde(default)]
    pub semantic_facts: bool,
    #[serde(default)]
    pub dependency_topology: bool,
    #[serde(default)]
    pub dependency_topology_metadata: bool,
}

/// Source matching defaults declared by a provider manifest.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ManifestSourceDefaults {
    pub default_extensions: Vec<String>,
    pub default_config_files: Vec<String>,
    pub default_source_roots: Vec<String>,
    pub default_ignored_path_prefixes: Vec<String>,
    #[serde(default)]
    pub default_project_markers: Vec<String>,
    #[serde(default)]
    pub default_dependency_markers: Vec<String>,
}

#[derive(Debug)]
/// In-memory runtime resolved from activation plus static provider manifests.
pub struct HookRuntime {
    pub project_root: String,
    pub providers: Vec<ActivatedProvider>,
}

/// Raw DTO boundary for an activated provider selected from a manifest.
///
/// The string fields preserve manifest and namespace identities exactly as they
/// are serialized for hook runtime activation.
#[derive(Debug)]
pub struct ActivatedProvider {
    pub manifest_id: String,
    pub manifest_digest: String,
    pub language_id: String,
    pub provider_id: String,
    pub binary: String,
    pub execution: ProviderExecution,
    pub provider_command_prefix: Vec<String>,
    pub namespace: String,
    pub package_roots: Vec<String>,
    pub source_extensions: Vec<String>,
    pub config_files: Vec<String>,
    pub source_roots: Vec<String>,
    pub ignored_path_prefixes: Vec<String>,
    pub search_capabilities: ProviderSearchCapabilities,
    pub policy: HookPolicy,
    pub routes: HookRoutes,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SourceSelectorKind {
    ExactPath,
    Pattern,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct ProviderSelectorMatch<'a> {
    pub provider: &'a ActivatedProvider,
    pub kind: SourceSelectorKind,
}

/// Parse activation JSON and resolve it against static provider manifests.
pub fn parse_activation(
    input: &str,
    manifests: &[ProviderManifest],
) -> Result<HookRuntime, AgentHookError> {
    let activation: HookActivation =
        serde_json::from_str(input).map_err(AgentHookError::InvalidActivation)?;
    activation.validate_protocol()?;
    resolve_activation(&activation, manifests)
}

/// Return the stable `sha256:` digest used by activation to pin a manifest.
pub fn provider_manifest_digest(manifest: &ProviderManifest) -> Result<String, AgentHookError> {
    let bytes = serde_json::to_vec(manifest).map_err(AgentHookError::InvalidOutput)?;
    let digest = Sha256::digest(bytes);
    Ok(format!("sha256:{digest:x}"))
}

fn resolve_activation(
    activation: &HookActivation,
    manifests: &[ProviderManifest],
) -> Result<HookRuntime, AgentHookError> {
    let mut providers = Vec::new();
    for activated in &activation.providers {
        let manifest = manifests
            .iter()
            .find(|manifest| manifest.manifest_id == activated.manifest_id)
            .ok_or_else(|| {
                AgentHookError::InvalidActivationConfig(format!(
                    "unknown provider manifest: {}",
                    activated.manifest_id
                ))
            })?;
        manifest.validate_protocol()?;
        let expected_digest = provider_manifest_digest(manifest)?;
        if activated.manifest_digest != expected_digest {
            return Err(AgentHookError::InvalidActivationConfig(format!(
                "provider manifest digest drift for {}: expected {}, got {}",
                activated.manifest_id, expected_digest, activated.manifest_digest
            )));
        }
        if activated.language_id != manifest.language_id
            || activated.provider_id != manifest.provider_id
            || activated.binary != manifest.binary
            || activated.execution != manifest.execution
        {
            return Err(AgentHookError::InvalidActivationConfig(format!(
                "provider activation does not match manifest identity: {}",
                activated.manifest_id
            )));
        }
        providers.push(ActivatedProvider {
            manifest_id: activated.manifest_id.clone(),
            manifest_digest: activated.manifest_digest.clone(),
            language_id: activated.language_id.clone(),
            provider_id: activated.provider_id.clone(),
            binary: activated.binary.clone(),
            execution: activated.execution,
            provider_command_prefix: activated.provider_command_prefix.clone(),
            namespace: manifest.namespace.clone(),
            package_roots: activated.coverage.package_roots.clone(),
            source_extensions: activated.coverage.source_extensions.clone(),
            config_files: activated.coverage.config_files.clone(),
            source_roots: activated.coverage.source_roots.clone(),
            ignored_path_prefixes: activated.coverage.ignored_path_prefixes.clone(),
            search_capabilities: manifest.search_capabilities.clone(),
            policy: manifest.policy.clone(),
            routes: manifest.routes.clone(),
        });
    }
    Ok(HookRuntime {
        project_root: activation.project_root.clone(),
        providers,
    })
}

impl HookActivation {
    fn validate_protocol(&self) -> Result<(), AgentHookError> {
        expect_field("schemaId", &self.schema_id, HOOK_ACTIVATION_SCHEMA_ID)?;
        expect_field(
            "schemaVersion",
            &self.schema_version,
            HOOK_ACTIVATION_SCHEMA_VERSION,
        )?;
        expect_field("protocolId", &self.protocol_id, HOOK_PROTOCOL_ID)?;
        expect_field(
            "protocolVersion",
            &self.protocol_version,
            HOOK_PROTOCOL_VERSION,
        )?;
        if !matches!(
            self.generated_by.runtime.as_str(),
            "asp" | "agent-semantic-hook"
        ) {
            return Err(AgentHookError::InvalidActivationConfig(format!(
                "invalid activation generatedBy.runtime: expected asp or agent-semantic-hook, got {}",
                self.generated_by.runtime
            )));
        }
        if self.providers.is_empty() {
            return Err(AgentHookError::InvalidActivationConfig(
                "activation must include at least one provider".to_string(),
            ));
        }
        Ok(())
    }
}

impl ProviderManifest {
    fn validate_protocol(&self) -> Result<(), AgentHookError> {
        expect_field("schemaId", &self.schema_id, PROVIDER_MANIFEST_SCHEMA_ID)?;
        expect_field(
            "schemaVersion",
            &self.schema_version,
            PROVIDER_MANIFEST_SCHEMA_VERSION,
        )?;
        expect_field("protocolId", &self.protocol_id, HOOK_PROTOCOL_ID)?;
        expect_field(
            "protocolVersion",
            &self.protocol_version,
            HOOK_PROTOCOL_VERSION,
        )?;
        Ok(())
    }
}

impl HookRuntime {
    pub(crate) fn providers_for_selector(&self, selector: &str) -> Vec<ProviderSelectorMatch<'_>> {
        let matcher = SourceSelectorMatcher::new(selector);
        self.providers
            .iter()
            .filter_map(|provider| {
                provider
                    .match_source_selector_with(&matcher)
                    .map(|kind| ProviderSelectorMatch { provider, kind })
            })
            .collect()
    }

    pub(crate) fn providers_for_raw_search_selector(
        &self,
        selector: &str,
    ) -> Vec<ProviderSelectorMatch<'_>> {
        let matcher = SourceSelectorMatcher::new(selector);
        self.providers
            .iter()
            .filter_map(|provider| {
                if provider
                    .ignored_path_prefixes
                    .iter()
                    .any(|prefix| matcher.is_ignored_by(prefix))
                {
                    return None;
                }
                (provider.glob_matches_source_selector(&matcher)
                    || (!matcher.has_glob
                        && provider.package_roots_match_search_token(matcher.normalized)))
                .then_some(ProviderSelectorMatch {
                    provider,
                    kind: if matcher.has_glob {
                        SourceSelectorKind::Pattern
                    } else {
                        SourceSelectorKind::ExactPath
                    },
                })
            })
            .collect()
    }
}

impl ActivatedProvider {
    fn matches_source_selector(&self, selector: &str) -> bool {
        self.match_source_selector(selector).is_some()
    }

    fn match_source_selector(&self, selector: &str) -> Option<SourceSelectorKind> {
        let matcher = SourceSelectorMatcher::new(selector);
        self.match_source_selector_with(&matcher)
    }

    fn match_source_selector_with(
        &self,
        selector: &SourceSelectorMatcher<'_>,
    ) -> Option<SourceSelectorKind> {
        if self
            .ignored_path_prefixes
            .iter()
            .any(|prefix| selector.is_ignored_by(prefix))
        {
            return None;
        }
        if self.glob_matches_source_selector(selector) {
            return Some(if selector.has_glob {
                SourceSelectorKind::Pattern
            } else {
                SourceSelectorKind::ExactPath
            });
        }
        if self
            .config_files
            .iter()
            .any(|config| selector.normalized.ends_with(config))
        {
            return Some(SourceSelectorKind::ExactPath);
        }
        None
    }

    pub(crate) fn matches_search_token(&self, token: &str) -> bool {
        let normalized = normalize_route_path(token);
        self.matches_source_selector(&normalized)
            || self.matches_source_directory_token(&normalized)
    }

    fn matches_source_directory_token(&self, normalized: &str) -> bool {
        self.source_root_matches_search_token(normalized)
            || self.package_roots_match_search_token(normalized)
    }

    fn package_roots_match_search_token(&self, normalized: &str) -> bool {
        self.package_roots
            .iter()
            .any(|root| self.package_root_matches_search_token(root, normalized))
    }

    fn package_root_matches_search_token(&self, package_root: &str, normalized: &str) -> bool {
        let package_root = normalize_route_path(package_root);
        let package_root = package_root.trim_end_matches('/');
        if package_root.is_empty() || package_root == "." {
            return false;
        }
        if normalized == package_root {
            return true;
        }
        normalized
            .strip_prefix(&format!("{package_root}/"))
            .is_some_and(|relative| self.source_root_matches_search_token(relative))
    }

    fn source_root_matches_search_token(&self, normalized: &str) -> bool {
        self.source_roots.iter().any(|root| {
            let root = normalize_route_path(root);
            let root = root.trim_end_matches('/');
            !root.is_empty() && (normalized == root || normalized.starts_with(&format!("{root}/")))
        })
    }

    fn glob_matches_source_selector(&self, selector: &SourceSelectorMatcher<'_>) -> bool {
        self.source_extensions
            .iter()
            .any(|extension| selector.targets_extension(extension))
    }

    pub(crate) fn route_from_template(
        &self,
        kind: DecisionRouteKind,
        template: &CommandTemplate,
        path: Option<&str>,
        query: Option<&str>,
    ) -> DecisionRoute {
        let route_context = path.map(|path| self.route_path_context(path));
        let route_path = route_context
            .as_ref()
            .map(|context| context.selector.as_str())
            .or(path)
            .unwrap_or("");
        let project_root = route_context
            .as_ref()
            .map(|context| context.project_root.as_str())
            .unwrap_or_else(|| self.default_route_project_root());
        let argv: Vec<String> = template
            .argv
            .iter()
            .map(|arg| {
                arg.replace("{path}", route_path)
                    .replace("{query}", query.unwrap_or(""))
                    .replace("{projectRoot}", project_root)
            })
            .collect();
        let argv = self.agent_facade_argv_from_provider_argv(argv);
        DecisionRoute {
            language_id: self.language_id.clone(),
            provider_id: self.provider_id.clone(),
            binary: "asp".to_string(),
            kind,
            argv,
            stdin_mode: template.stdin_mode,
        }
    }

    pub(crate) fn agent_facade_argv<I, S>(&self, args: I) -> Vec<String>
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        let mut argv = vec!["asp".to_string(), self.language_id.clone()];
        argv.extend(args.into_iter().map(Into::into));
        argv
    }

    pub(crate) fn agent_facade_argv_from_provider_argv(&self, argv: Vec<String>) -> Vec<String> {
        if argv.first().is_some_and(|command| command == "asp") {
            return argv;
        }
        if argv.first().is_some_and(|command| command == &self.binary) {
            return self.agent_facade_argv(argv.into_iter().skip(1));
        }
        if !self.provider_command_prefix.is_empty()
            && argv.starts_with(&self.provider_command_prefix)
        {
            return self
                .agent_facade_argv(argv.into_iter().skip(self.provider_command_prefix.len()));
        }
        argv
    }

    pub(crate) fn route_path_context(&self, path: &str) -> ProviderRoutePathContext {
        let normalized = normalize_route_path(path);
        for root in self.package_roots_by_specificity() {
            if root == "." {
                continue;
            }
            if normalized == root {
                return ProviderRoutePathContext {
                    selector: ".".to_string(),
                    project_root: root,
                };
            }
            if let Some(selector) = normalized.strip_prefix(&format!("{root}/")) {
                return ProviderRoutePathContext {
                    selector: selector.to_string(),
                    project_root: root,
                };
            }
        }
        ProviderRoutePathContext {
            selector: normalized,
            project_root: self.default_route_project_root().to_string(),
        }
    }

    fn default_route_project_root(&self) -> &str {
        self.package_roots
            .iter()
            .find(|root| root.as_str() == ".")
            .map(String::as_str)
            .or_else(|| self.package_roots.first().map(String::as_str))
            .unwrap_or(".")
    }

    fn package_roots_by_specificity(&self) -> Vec<String> {
        let mut roots = self.package_roots.clone();
        roots.sort_by(|left, right| right.len().cmp(&left.len()).then(left.cmp(right)));
        roots
    }
}

pub(crate) struct ProviderRoutePathContext {
    pub(crate) selector: String,
    pub(crate) project_root: String,
}

fn normalize_route_path(path: &str) -> String {
    path.replace('\\', "/").trim_start_matches("./").to_string()
}

struct SourceSelectorMatcher<'a> {
    normalized: &'a str,
    has_glob: bool,
    extension_glob: Option<GlobSet>,
}

impl<'a> SourceSelectorMatcher<'a> {
    fn new(selector: &'a str) -> Self {
        let normalized = normalize_source_selector(selector);
        let has_glob = selector_has_glob(normalized);
        let basename = basename_pattern(normalized).to_ascii_lowercase();
        let extension_pattern = basename_extension_pattern(&basename);
        Self {
            normalized,
            has_glob,
            extension_glob: extension_pattern.and_then(build_glob_set),
        }
    }

    fn is_ignored_by(&self, prefix: &str) -> bool {
        self.normalized == prefix || self.normalized.starts_with(&format!("{prefix}/"))
    }

    fn targets_extension(&self, extension: &str) -> bool {
        let extension = extension.trim_start_matches('.').to_ascii_lowercase();
        self.extension_glob
            .as_ref()
            .is_some_and(|glob_set| glob_set.is_match(extension))
    }
}

fn build_glob_set(pattern: &str) -> Option<GlobSet> {
    let glob = GlobBuilder::new(pattern)
        .literal_separator(false)
        .backslash_escape(false)
        .build()
        .ok()?;
    let mut builder = GlobSetBuilder::new();
    builder.add(glob);
    builder.build().ok()
}

fn basename_pattern(selector: &str) -> &str {
    selector
        .trim_end_matches('/')
        .rsplit('/')
        .next()
        .unwrap_or(selector)
}

fn basename_extension_pattern(basename: &str) -> Option<&str> {
    let (_, _, last_literal_dot) = basename.char_indices().fold(
        (0usize, 0usize, None),
        |(bracket_depth, brace_depth, last_literal_dot), (index, character)| match character {
            '[' => (bracket_depth + 1, brace_depth, last_literal_dot),
            ']' if bracket_depth > 0 => (bracket_depth - 1, brace_depth, last_literal_dot),
            '{' if bracket_depth == 0 => (bracket_depth, brace_depth + 1, last_literal_dot),
            '}' if bracket_depth == 0 && brace_depth > 0 => {
                (bracket_depth, brace_depth - 1, last_literal_dot)
            }
            '.' if bracket_depth == 0 && brace_depth == 0 => {
                (bracket_depth, brace_depth, Some(index))
            }
            _ => (bracket_depth, brace_depth, last_literal_dot),
        },
    );
    let start = last_literal_dot? + 1;
    (start < basename.len()).then_some(&basename[start..])
}

fn selector_has_glob(path: &str) -> bool {
    path.chars()
        .any(|character| matches!(character, '*' | '?' | '[' | ']' | '{' | '}'))
}

fn expect_field(name: &str, actual: &str, expected: &str) -> Result<(), AgentHookError> {
    if actual == expected {
        return Ok(());
    }
    Err(AgentHookError::InvalidActivationConfig(format!(
        "invalid activation {name}: expected {expected}, got {actual}"
    )))
}
