-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.Audit.HookExecutionPlane

open Lean Elab Command
open ASPProof.HookExecutionPlane
open ASPProof.Audit.HookExecutionPlane

#check wildcard_dispatch_does_not_imply_runtime_dispatch
#check codex_hook_has_one_plugin_bundle_authority
#check plugin_install_cannot_mutate_agent_or_runtime_lifecycle
#check decision_authority_survives_diagnostic_projection_timeout
#check bounded_scalar_document_predicate_is_not_a_bulk_dump
#check decision_projection_never_waits_for_event_writer_lock
#check unavailable_projection_cannot_reenter_runtime_or_change_authority
#check codex_hook_uses_canonical_host_event_name
#check unrelated_action_is_local_zero_io
#check source_policy_never_enters_runtime
#check command_policy_never_enters_runtime
#check nested_policy_never_enters_runtime
#check missing_identity_fails_closed_without_runtime_dependency
#check unrelated_typed_action_path_cannot_create_read_policy
#check missing_identity_path_remains_local_fail_closed
#check structured_document_axis_cannot_capture_provider_source
#check provider_source_axis_cannot_capture_structured_document
#check hook_runtime_server_is_unreachable
#check org_contract_interactive_owns_choice_description
#check hook_execution_router_cannot_invent_choice
#check org_projection_does_not_create_transition_authority
#check hook_recovery_can_reference_but_not_reimplement_choice_plane
#check org_choice_plane_excludes_every_legacy_rust_surface
#check response_owner_flushes_before_immediate_termination
#check hook_deadline_cannot_depend_on_process_global_cleanup
#check end_to_end_budget_implies_entry_execution_budget
#check hook_data_path_cannot_reconcile_supervisor
#check hook_data_path_cannot_contact_runtime_server
#check hook_data_path_cannot_install_binary
#check local_policy_failure_cannot_recommend_server_reconcile
#check local_policy_failure_has_configuration_independent_diagnostic
#check nested_deadlines_leave_cleanup_slack
#check timed_out_stateful_call_cannot_leave_runtime_healthy
#check concurrency_cap_is_terminal_not_a_queue
#check undrained_resources_are_detected
#check isolated_test_home_cannot_target_user_supervisor

#print axioms wildcard_dispatch_does_not_imply_runtime_dispatch
#print axioms codex_hook_has_one_plugin_bundle_authority
#print axioms plugin_install_cannot_mutate_agent_or_runtime_lifecycle
#print axioms decision_authority_survives_diagnostic_projection_timeout
#print axioms bounded_scalar_document_predicate_is_not_a_bulk_dump
#print axioms decision_projection_never_waits_for_event_writer_lock
#print axioms unavailable_projection_cannot_reenter_runtime_or_change_authority
#print axioms codex_hook_uses_canonical_host_event_name
#print axioms unrelated_action_is_local_zero_io
#print axioms source_policy_never_enters_runtime
#print axioms command_policy_never_enters_runtime
#print axioms nested_policy_never_enters_runtime
#print axioms missing_identity_fails_closed_without_runtime_dependency
#print axioms unrelated_typed_action_path_cannot_create_read_policy
#print axioms missing_identity_path_remains_local_fail_closed
#print axioms structured_document_axis_cannot_capture_provider_source
#print axioms provider_source_axis_cannot_capture_structured_document
#print axioms hook_runtime_server_is_unreachable
#print axioms org_contract_interactive_owns_choice_description
#print axioms hook_execution_router_cannot_invent_choice
#print axioms org_projection_does_not_create_transition_authority
#print axioms hook_recovery_can_reference_but_not_reimplement_choice_plane
#print axioms org_choice_plane_excludes_every_legacy_rust_surface
#print axioms response_owner_flushes_before_immediate_termination
#print axioms hook_deadline_cannot_depend_on_process_global_cleanup
#print axioms end_to_end_budget_implies_entry_execution_budget
#print axioms hook_data_path_cannot_reconcile_supervisor
#print axioms hook_data_path_cannot_contact_runtime_server
#print axioms hook_data_path_cannot_install_binary
#print axioms local_policy_failure_cannot_recommend_server_reconcile
#print axioms local_policy_failure_has_configuration_independent_diagnostic
#print axioms nested_deadlines_leave_cleanup_slack
#print axioms timed_out_stateful_call_cannot_leave_runtime_healthy
#print axioms concurrency_cap_is_terminal_not_a_queue
#print axioms undrained_resources_are_detected
#print axioms isolated_test_home_cannot_target_user_supervisor

run_elab do
  let json ← ASPProof.Audit.HookExecutionPlane.auditJson
  IO.FS.writeFile
    "receipts/hook-execution-plane-audit-v1.json"
    json.pretty
