import ASPProof.Audit.HookGenerationAdmissionNonBlocking

open ASPProof.HookGenerationAdmissionNonBlocking
open ASPProof.Audit.HookGenerationAdmissionNonBlocking

#check failed_admission_preserves_generic_commands
#check failed_admission_preserves_control_plane_recovery
#check failed_admission_does_not_release_direct_source_read
#check failed_generation_query_remains_data_plane_fail_closed
#check failed_admission_cannot_globally_deadlock_the_hook
#check hook_allow_does_not_imply_generation_query_execution

#print axioms failed_admission_preserves_generic_commands
#print axioms failed_admission_preserves_control_plane_recovery
#print axioms failed_admission_does_not_release_direct_source_read
#print axioms failed_generation_query_remains_data_plane_fail_closed
#print axioms failed_admission_cannot_globally_deadlock_the_hook
#print axioms hook_allow_does_not_imply_generation_query_execution
