-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.SearchRouteTriadHandoffIdentity

#print axioms ASPProof.SearchRouteTriadHandoffIdentity.admitted_handoff_has_one_receipt_chain
#print axioms ASPProof.SearchRouteTriadHandoffIdentity.admitted_handoff_has_all_gates
#print axioms ASPProof.SearchRouteTriadHandoffIdentity.same_chain_and_ready_gates_admit
#print axioms ASPProof.SearchRouteTriadHandoffIdentity.invalid_execution_configuration_blocks_admission
#print axioms ASPProof.SearchRouteTriadHandoffIdentity.unauthenticated_chain_identity_blocks_admission
#print axioms ASPProof.SearchRouteTriadHandoffIdentity.unreplayed_normalized_audit_blocks_admission
#print axioms ASPProof.SearchRouteTriadHandoffIdentity.all_green_but_spliced_receipts_are_not_admitted
#print axioms ASPProof.SearchRouteTriadHandoffIdentity.fully_ready_handoff_is_admitted
#print axioms ASPProof.SearchRouteTriadHandoffIdentity.generator_only_audit_is_not_admitted
#print axioms ASPProof.SearchRouteTriadHandoffIdentity.observed_v1_preflight_failure_is_not_admitted
