-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.SearchRouteTriadRelationshipContract

#print axioms ASPProof.SearchRouteTriadRelationshipContract.exact_binding_has_identifier_binding
#print axioms ASPProof.SearchRouteTriadRelationshipContract.changed_clause_digest_invalidates
#print axioms ASPProof.SearchRouteTriadRelationshipContract.changed_dependency_set_invalidates
#print axioms ASPProof.SearchRouteTriadRelationshipContract.identifier_only_binding_accepts_changed_semantics
#print axioms ASPProof.SearchRouteTriadRelationshipContract.exact_binding_rejects_changed_semantics
#print axioms ASPProof.SearchRouteTriadRelationshipContract.subset_check_accepts_underdeclared_dependencies
#print axioms ASPProof.SearchRouteTriadRelationshipContract.exact_coverage_rejects_underdeclared_dependencies
#print axioms ASPProof.SearchRouteTriadRelationshipContract.underdeclared_coverage_blocks_gate
#print axioms ASPProof.SearchRouteTriadRelationshipContract.stale_clause_blocks_gate
#print axioms ASPProof.SearchRouteTriadRelationshipContract.admitted_gate_has_org_contract
#print axioms ASPProof.SearchRouteTriadRelationshipContract.exact_digests_without_org_contract_are_not_admitted
#print axioms ASPProof.SearchRouteTriadRelationshipContract.contract_and_exact_evidence_admit
#print axioms ASPProof.SearchRouteTriadRelationshipContract.unrelated_clause_change_preserves_local_binding
