import ASPProof.SearchRoutePythonLeanSubagentTriad

#print axioms ASPProof.SearchRoutePythonLeanSubagentTriad.complete_evidence_is_admitted
#print axioms ASPProof.SearchRoutePythonLeanSubagentTriad.missing_lean_receipt_blocks_admission
#print axioms ASPProof.SearchRoutePythonLeanSubagentTriad.missing_golden_agreement_blocks_admission
#print axioms ASPProof.SearchRoutePythonLeanSubagentTriad.parent_confirmation_does_not_close_nested_receipt
#print axioms ASPProof.SearchRoutePythonLeanSubagentTriad.observed_nested_receipt_is_not_admitted
#print axioms ASPProof.SearchRoutePythonLeanSubagentTriad.observed_parent_receipt_is_admitted
