import ASPProof.SemanticProjectionRuntimeWrapping

open ASPProof.SemanticProjectionRuntimeWrapping

#check provider_payload_cannot_supply_envelope_authority
#check verified_binding_preserves_runtime_authority
#check payload_digest_mismatch_rejected
#check root_digest_does_not_replace_generation_binding
