[languages.rust]
repo = "tao3k/rust-lang-project-harness"
version = "v0.1.2"
downloadBaseUrl = "https://github.com/tao3k/rust-lang-project-harness/releases/download/v0.1.2"
supportedTargets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "x86_64-pc-windows-msvc",
]

[languages.typescript]
repo = "tao3k/typescript-lang-project-harness"
version = "v0.1.0"
downloadBaseUrl = "https://github.com/tao3k/typescript-lang-project-harness/releases/download/v0.1.0"
supportedTargets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
]

[languages.python]
repo = "tao3k/asp-python"
version = "v0.1.0"
downloadBaseUrl = "https://github.com/tao3k/asp-python/releases/download/v0.1.0"
supportedTargets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
]

[languages.julia]
repo = "JuliaCN/AspJulia.jl"
version = "v0.1.0"
archivePrefix = "asp-julia"
archiveBinary = "asp-julia"
downloadBaseUrl = "https://github.com/JuliaCN/AspJulia.jl/releases/download/v0.1.0"
supportedTargets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
]

[languages.gerbil-scheme]
repo = "tao3k/asp-gerbil-scheme"
version = "v0.1.0"
downloadBaseUrl = "https://github.com/tao3k/asp-gerbil-scheme/releases/download/v0.1.0"
archivePrefix = "asp-gerbil-scheme"
archiveBinary = "asp-gerbil-scheme"
requireNativeBinary = true
supportedTargets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
]
