//! Command tree for the `asp` binary.

mod ast_patch;
mod client_backend_worker;
mod dispatch;
mod document_provider;
mod graph;
mod healthcheck;
mod hook;
mod hook_enforcement;
mod hook_runtime;
mod hook_runtime_context;
mod protocol_binary;
mod protocol_version;
mod provider;
mod provider_process;
mod provider_roots;
mod query_direct_read;
mod query_owner;
mod root_language_facade;
mod search_config;
mod search_failure_render;
mod search_language_files;
mod search_pipe;
mod search_pipe_action_frontier;
mod search_pipe_action_model;
mod search_pipe_actions;
mod search_pipe_args;
mod search_pipe_candidates;
mod search_pipe_dependency_facts;
mod search_pipe_graph_turbo;
mod search_pipe_meta;
mod search_pipe_model;
mod search_pipe_native_finder;
mod search_pipe_owner_query;
mod search_pipe_plan;
mod search_pipe_provider_facts;
mod search_pipe_quality;
mod search_pipe_query_evidence;
mod search_pipe_query_model;
mod search_pipe_query_pack;
mod search_pipe_read_memory;
mod search_pipe_render;
mod search_pipe_source;
mod search_pipe_surfaces;
mod search_pipe_view;
mod search_query_wrapper;
mod search_query_wrapper_candidates;
mod search_query_wrapper_frontier;
mod search_query_wrapper_model;
mod search_query_wrapper_quality;
mod search_suggest;
mod source_access;

pub(crate) use dispatch::run_protocol_command;
pub(in crate::command) use hook_enforcement::codex_enforcement_report;
pub(in crate::command) use hook_runtime_context::payload_indicates_subagent_context;
pub(in crate::command) use protocol_binary::{
    ensure_protocol_binary_installed_for_path, protocol_binary_on_path,
};
pub(in crate::command) use protocol_version::protocol_version_line;
