use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

pub(crate) const ROOT_BLOCK_BEGIN: &str = "# BEGIN semantic-agent-hook agent hooks";
pub(crate) const ROOT_BLOCK_END: &str = "# END semantic-agent-hook agent hooks";

const TRUST_BLOCK_END: &str = "# END semantic-agent-hook trusted hook state";
const LEGACY_BLOCKS: [(&str, &str); 3] = [
    (
        "# BEGIN ts-harness agent hooks",
        "# END ts-harness agent hooks",
    ),
    (
        "# BEGIN py-harness agent hooks",
        "# END py-harness agent hooks",
    ),
    (
        "# BEGIN rs-harness agent hooks",
        "# END rs-harness agent hooks",
    ),
];
const CODEX_TOOL_MATCHER: &str = ".*";

#[derive(Debug)]
pub(crate) struct CodexUserTrustStatus {
    pub trust_config_path: PathBuf,
    pub trusted: bool,
    pub missing_events: Vec<String>,
}

#[derive(Debug, Clone, Copy)]
struct CodexHookEvent {
    event: &'static str,
    state_label: &'static str,
    matcher: Option<&'static str>,
    status: &'static str,
    hook_event: &'static str,
}

pub(crate) fn codex_hook_block() -> String {
    let events = codex_hook_events();
    let body = events
        .iter()
        .map(codex_hook_event_block)
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "{ROOT_BLOCK_BEGIN}\n# Generated by `semantic-agent-hook install --client codex`.\n# Root dispatcher for language-owned semantic hook profiles.\n\n{body}\n{ROOT_BLOCK_END}"
    )
}

pub(crate) fn install_codex_user_trust_state(
    project_config_path: &Path,
) -> Result<PathBuf, String> {
    let project_config_path = fs::canonicalize(project_config_path).map_err(|error| {
        format!(
            "failed to resolve project Codex config {}: {error}",
            project_config_path.display()
        )
    })?;
    let codex_home = codex_home_path()?;
    fs::create_dir_all(&codex_home)
        .map_err(|error| format!("failed to create {}: {error}", codex_home.display()))?;
    let user_config_path = codex_home.join("config.toml");
    let existing = fs::read_to_string(&user_config_path).unwrap_or_default();
    if user_config_path.is_file() {
        validate_codex_config_toml(&existing).map_err(|error| {
            format!(
                "refusing to write invalid Codex user config {}: {error}",
                user_config_path.display()
            )
        })?;
    }
    let trust_block = codex_trust_state_block(&project_config_path);
    let merged = merge_codex_trust_config(&existing, &project_config_path, &trust_block);
    validate_codex_config_toml(&merged).map_err(|error| {
        format!(
            "refusing to write invalid Codex user trust config {}: {error}",
            user_config_path.display()
        )
    })?;
    fs::write(&user_config_path, merged.as_bytes())
        .map_err(|error| format!("failed to write {}: {error}", user_config_path.display()))?;
    Ok(user_config_path)
}

pub(crate) fn codex_user_trust_state_status(
    project_config_path: &Path,
) -> Result<CodexUserTrustStatus, String> {
    let project_config_path = fs::canonicalize(project_config_path).map_err(|error| {
        format!(
            "failed to resolve project Codex config {}: {error}",
            project_config_path.display()
        )
    })?;
    let trust_config_path = codex_home_path()?.join("config.toml");
    let content = fs::read_to_string(&trust_config_path).unwrap_or_default();
    let parsed =
        toml::from_str::<toml::Value>(&content)
            .unwrap_or(toml::Value::Table(
                toml::map::Map::<String, toml::Value>::new(),
            ));
    let state = parsed
        .get("hooks")
        .and_then(toml::Value::as_table)
        .and_then(|hooks| hooks.get("state"))
        .and_then(toml::Value::as_table);
    let missing_events = codex_hook_events()
        .iter()
        .filter_map(|event| {
            let key = format!(
                "{}:{}:0:0",
                project_config_path.display(),
                event.state_label
            );
            let expected_hash = codex_hook_trusted_hash(event);
            let trusted = state
                .and_then(|state| state.get(&key))
                .and_then(toml::Value::as_table)
                .and_then(|entry| entry.get("trusted_hash"))
                .and_then(toml::Value::as_str)
                .is_some_and(|actual_hash| actual_hash == expected_hash);
            (!trusted).then(|| event.hook_event.to_string())
        })
        .collect::<Vec<_>>();
    Ok(CodexUserTrustStatus {
        trust_config_path,
        trusted: missing_events.is_empty(),
        missing_events,
    })
}

pub(crate) fn validate_codex_config_toml(content: &str) -> Result<(), String> {
    toml::from_str::<toml::Value>(content)
        .map(|_| ())
        .map_err(|error| error.to_string())
}

pub(crate) fn merge_codex_config(existing: &str, block: &str) -> String {
    let mut content = existing.to_string();
    for (begin, end) in LEGACY_BLOCKS {
        content = remove_managed_block(&content, begin, end);
    }
    content = remove_managed_block(&content, ROOT_BLOCK_BEGIN, ROOT_BLOCK_END);
    content = ensure_codex_required_features(&content);
    let prefix = content.trim();
    if prefix.is_empty() {
        format!(
            "[features]\nhooks = true\nunified_exec = true\n\n{}\n",
            block.trim_end()
        )
    } else {
        format!("{}\n\n{}\n", prefix, block.trim_end())
    }
}

fn codex_hook_events() -> [CodexHookEvent; 8] {
    [
        CodexHookEvent {
            event: "SessionStart",
            state_label: "session_start",
            matcher: Some("startup|resume|clear|compact"),
            status: "Loading semantic agent hook profiles",
            hook_event: "session-start",
        },
        CodexHookEvent {
            event: "UserPromptSubmit",
            state_label: "user_prompt_submit",
            matcher: None,
            status: "Planning semantic search flow",
            hook_event: "user-prompt",
        },
        CodexHookEvent {
            event: "PreToolUse",
            state_label: "pre_tool_use",
            matcher: Some(CODEX_TOOL_MATCHER),
            status: "Checking semantic search flow",
            hook_event: "pre-tool",
        },
        CodexHookEvent {
            event: "PermissionRequest",
            state_label: "permission_request",
            matcher: Some(CODEX_TOOL_MATCHER),
            status: "Checking semantic approval flow",
            hook_event: "permission-request",
        },
        CodexHookEvent {
            event: "PostToolUse",
            state_label: "post_tool_use",
            matcher: Some(CODEX_TOOL_MATCHER),
            status: "Updating semantic search flow state",
            hook_event: "post-tool",
        },
        CodexHookEvent {
            event: "SubagentStart",
            state_label: "subagent_start",
            matcher: Some(CODEX_TOOL_MATCHER),
            status: "Preparing semantic subagent context",
            hook_event: "subagent-start",
        },
        CodexHookEvent {
            event: "SubagentStop",
            state_label: "subagent_stop",
            matcher: Some(CODEX_TOOL_MATCHER),
            status: "Checking semantic subagent evidence",
            hook_event: "subagent-stop",
        },
        CodexHookEvent {
            event: "Stop",
            state_label: "stop",
            matcher: None,
            status: "Checking semantic changed files",
            hook_event: "stop",
        },
    ]
}

fn codex_hook_event_block(event: &CodexHookEvent) -> String {
    let matcher_line = event
        .matcher
        .map(|value| format!("matcher = {}\n\n", toml_basic_string(value)))
        .unwrap_or_else(|| "\n".to_string());
    let command = codex_hook_command(event.hook_event);
    format!(
        "[[hooks.{event_name}]]\n{matcher_line}[[hooks.{event_name}.hooks]]\ntype = \"command\"\ntimeout = 5\nstatusMessage = \"{status}\"\ncommand = '''\n{command}'''",
        event_name = event.event,
        status = event.status,
    )
}

fn codex_hook_command(hook_event: &str) -> String {
    format!(
        "repo_root=\"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\"\ncd \"$repo_root\"\nprofiles=\"$repo_root/.codex/semantic-agent-hook/profiles.json\"\nexec semantic-agent-hook hook --client codex {hook_event} --profiles \"$profiles\"\n"
    )
}

fn codex_hook_state_block(config_source_path: &Path, event: &CodexHookEvent) -> String {
    let key = format!("{}:{}:0:0", config_source_path.display(), event.state_label);
    let hash = codex_hook_trusted_hash(event);
    format!(
        "[hooks.state.{}]\ntrusted_hash = {}",
        toml_basic_string(&key),
        toml_basic_string(&hash)
    )
}

fn codex_home_path() -> Result<PathBuf, String> {
    if let Some(path) = env::var_os("CODEX_HOME").filter(|value| !value.is_empty()) {
        return Ok(PathBuf::from(path));
    }
    env::var_os("HOME")
        .filter(|value| !value.is_empty())
        .map(|home| PathBuf::from(home).join(".codex"))
        .ok_or_else(|| {
            "missing CODEX_HOME and HOME; cannot write Codex hook trust state".to_string()
        })
}

fn codex_trust_state_block(config_source_path: &Path) -> String {
    let state = codex_hook_events()
        .iter()
        .map(|event| codex_hook_state_block(config_source_path, event))
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "{}\n{state}\n{TRUST_BLOCK_END}",
        codex_trust_block_begin(config_source_path)
    )
}

fn codex_trust_block_begin(config_source_path: &Path) -> String {
    format!(
        "# BEGIN semantic-agent-hook trusted hook state: {}",
        config_source_path.display()
    )
}

fn merge_codex_trust_config(existing: &str, config_source_path: &Path, block: &str) -> String {
    let content = remove_managed_block(
        existing,
        &codex_trust_block_begin(config_source_path),
        TRUST_BLOCK_END,
    );
    let content = remove_hook_state_entries_for_config(&content, config_source_path);
    let prefix = content.trim();
    if prefix.is_empty() {
        format!("{}\n", block.trim_end())
    } else {
        format!("{}\n\n{}\n", prefix, block.trim_end())
    }
}

fn remove_hook_state_entries_for_config(existing: &str, config_source_path: &Path) -> String {
    let escaped_path = toml_basic_string(&config_source_path.display().to_string());
    let state_prefix = format!(
        "[hooks.state.{}:",
        escaped_path
            .strip_suffix('"')
            .expect("TOML string always ends with quote")
    );
    existing
        .lines()
        .scan(false, |skipping, line| {
            let trimmed = line.trim();
            if trimmed.starts_with("[hooks.state.") && trimmed.starts_with(&state_prefix) {
                *skipping = true;
                return Some(None);
            }
            if *skipping && trimmed.starts_with('[') {
                *skipping = false;
            }
            Some((!*skipping).then_some(line))
        })
        .flatten()
        .collect::<Vec<_>>()
        .join("\n")
}

fn codex_hook_trusted_hash(event: &CodexHookEvent) -> String {
    let mut identity = serde_json::Map::new();
    identity.insert(
        "event_name".to_string(),
        Value::String(event.state_label.to_string()),
    );
    if let Some(matcher) = event.matcher {
        identity.insert("matcher".to_string(), Value::String(matcher.to_string()));
    }
    identity.insert(
        "hooks".to_string(),
        Value::Array(vec![json!({
            "type": "command",
            "command": codex_hook_command(event.hook_event),
            "timeout": 5,
            "async": false,
            "statusMessage": event.status,
        })]),
    );
    version_for_codex_hook_identity(Value::Object(identity))
}

fn version_for_codex_hook_identity(value: Value) -> String {
    let canonical = canonical_json(value);
    let serialized = serde_json::to_vec(&canonical).unwrap_or_default();
    let hash = Sha256::digest(serialized);
    let hex = hash
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    format!("sha256:{hex}")
}

fn canonical_json(value: Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut keys = map.keys().cloned().collect::<Vec<_>>();
            keys.sort();
            let mut sorted = serde_json::Map::new();
            for key in keys {
                if let Some(value) = map.get(&key) {
                    sorted.insert(key, canonical_json(value.clone()));
                }
            }
            Value::Object(sorted)
        }
        Value::Array(items) => Value::Array(items.into_iter().map(canonical_json).collect()),
        other => other,
    }
}

fn toml_basic_string(value: &str) -> String {
    let mut output = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            c if c.is_control() => output.push_str(&format!("\\u{:04X}", c as u32)),
            c => output.push(c),
        }
    }
    output.push('"');
    output
}

fn ensure_codex_required_features(existing: &str) -> String {
    let mut table = String::new();
    let mut lines = existing
        .lines()
        .filter_map(|line| {
            let trimmed = line.trim();
            let skip = is_top_level_codex_feature(&table, trimmed);
            if let Some(header) = toml_table_header(trimmed) {
                table = header;
            }
            (!skip).then(|| line.to_string())
        })
        .collect::<Vec<_>>();

    let Some(features_start) = lines
        .iter()
        .position(|line| toml_table_header(line.trim()).as_deref() == Some("features"))
    else {
        let body = lines.join("\n").trim().to_string();
        return if body.is_empty() {
            "[features]\nhooks = true\nunified_exec = true".to_string()
        } else {
            format!("[features]\nhooks = true\nunified_exec = true\n\n{body}")
        };
    };

    let mut features_end = lines
        .iter()
        .enumerate()
        .skip(features_start + 1)
        .find_map(|(index, line)| toml_table_header(line.trim()).map(|_| index))
        .unwrap_or(lines.len());

    for key in ["hooks", "unified_exec"] {
        ensure_codex_feature_key(&mut lines, features_start, &mut features_end, key);
    }
    lines.join("\n")
}

fn ensure_codex_feature_key(
    lines: &mut Vec<String>,
    features_start: usize,
    features_end: &mut usize,
    key: &str,
) {
    if let Some(index) = lines[features_start + 1..*features_end]
        .iter()
        .position(|line| is_codex_feature_key(line.trim(), key))
        .map(|offset| features_start + 1 + offset)
    {
        lines[index] = format!("{key} = true");
    } else {
        lines.insert(*features_end, format!("{key} = true"));
        *features_end += 1;
    }
}

fn is_top_level_codex_feature(table: &str, trimmed: &str) -> bool {
    table.is_empty()
        && ["hooks", "unified_exec"]
            .iter()
            .any(|key| is_codex_feature_key(trimmed, key))
}

fn is_codex_feature_key(trimmed: &str, key: &str) -> bool {
    if trimmed.is_empty() || trimmed.starts_with('#') {
        return false;
    }
    trimmed
        .split_once('=')
        .is_some_and(|(candidate, _)| candidate.trim() == key)
}

fn toml_table_header(trimmed: &str) -> Option<String> {
    if !trimmed.starts_with('[') || !trimmed.ends_with(']') {
        return None;
    }
    let header = trimmed.trim_matches(['[', ']']).trim();
    (!header.is_empty()).then(|| header.to_string())
}

fn remove_managed_block(existing: &str, begin: &str, end: &str) -> String {
    let mut content = existing.to_string();
    while let Some(start) = content.find(begin) {
        let Some(relative_end) = content[start..].find(end) else {
            break;
        };
        let end_index = start + relative_end + end.len();
        content.replace_range(start..end_index, "");
    }
    content.trim().to_string()
}
