# SPDX-FileCopyrightText: 2026 tao3k team and Contributors
#
# SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

[package]
name = "agent-semantic-tree-sitter"
license.workspace = true
version = "0.1.0"
edition.workspace = true

[dependencies]
agent-semantic-scheme-syntax = { path = "../agent-semantic-scheme-syntax" }
agent-semantic-client-protocol = { path = "../agent-semantic-client-protocol" }
agent-semantic-provider-protocol.workspace = true
base64.workspace = true
blake3.workspace = true
regex-automata.workspace = true
serde_json.workspace = true
tree-sitter.workspace = true
tree-sitter-tsquery.workspace = true

[build-dependencies]
asp-rust-project-harness-policy = { workspace = true }

[dev-dependencies]
asp-rust = { workspace = true }
