import ASPProof.AgentSessionHostRegistryAuthenticatedProjection

namespace ASPProof.Audit.AgentSessionHostRegistryAuthenticatedProjection

open ASPProof.AgentSessionHostRegistryAuthenticatedProjection

#print axioms authenticated_manifest_is_canonical
#print axioms authenticated_manifest_root_is_exact
#print axioms authenticated_inclusion_is_member
#print axioms authenticated_exclusion_is_absent
#print axioms authenticated_inclusion_exclusion_conflict_impossible
#print axioms conflicting_unbound_claims_constructible
#print axioms digest_collision_has_one_root
#print axioms injective_commitment_identifies_input
#print axioms authenticated_delta_base_root_is_exact
#print axioms authenticated_delta_next_root_is_exact
#print axioms authenticated_delta_revision_advances
#print axioms authenticated_delta_semantic_input_changes
#print axioms authenticated_delta_root_changes
#print axioms authenticated_delta_floor_is_monotone
#print axioms authenticated_delta_preserves_other_records
#print axioms authenticated_delta_preserves_other_entries
#print axioms authenticated_delta_preserves_covered_tombstones
#print axioms naive_tombstone_resurrection_constructible
#print axioms naive_tombstone_resurrection_breaks_preservation
#print axioms stale_base_claim_constructible
#print axioms stale_base_claim_cannot_match_current
#print axioms authenticated_projection_cas_after_is_authenticated
#print axioms authenticated_projection_cas_uses_current_revision
#print axioms authenticated_projection_cas_after_is_choice
#print axioms authenticated_projection_same_head_is_unique

end ASPProof.Audit.AgentSessionHostRegistryAuthenticatedProjection
