import ASPProof.AgentSessionLifecycleConcurrentLinearizability

open ASPProof.AgentSessionLifecycleConcurrentLinearizability

#print axioms linearizable_claim_has_one_controller
#print axioms linearizable_claim_has_one_payload
#print axioms non_atomic_claim_can_express_two_winners
#print axioms non_atomic_two_winners_violate_linearizable_claim
#print axioms receipt_index_has_one_effect_identity
#print axioms receipt_index_rejects_payload_conflict
#print axioms binding_ledger_has_one_child_per_generation
#print axioms binding_ledger_has_one_target_per_generation
#print axioms terminal_ledger_has_one_effect
#print axioms terminal_ledger_rejects_command_conflict
#print axioms empty_claim_snapshot_attempts_reservation_cas
#print axioms matching_claim_snapshot_reuses_committed_intent
#print axioms matching_key_with_payload_drift_is_rejected
#print axioms different_key_is_rejected_while_slot_occupied
#print axioms restarted_controller_reuses_durable_intent
#print axioms claim_before_receipt
#print axioms receipt_before_binding
#print axioms claim_before_binding
#print axioms binding_cannot_precede_claim
