import ASPProof.AgentSessionLifecycleCrashRecovery

open ASPProof.AgentSessionLifecycleCrashRecovery

#print axioms matching_receipt_binds_intent_key
#print axioms matching_receipt_binds_generation
#print axioms matching_receipt_binds_payload
#print axioms idempotent_host_replay_preserves_effect_identity
#print axioms different_intent_key_rejects_receipt
#print axioms different_payload_rejects_receipt
#print axioms retirement_accepted_before_receipt_persists_receipt
#print axioms release_receipt_before_delivered_cas_commits_release
#print axioms typed_start_before_binding_commit_commits_binding
#print axioms bind_receipt_before_binding_commit_commits_binding
#print axioms missing_durable_intent_blocks_recovery
#print axioms committed_state_is_idempotent
#print axioms unknown_acceptance_polls_same_intent
#print axioms exhausted_poll_budget_is_explicitly_blocked
#print axioms committed_recovery_has_no_self_loop
#print axioms committed_recovery_has_no_two_cycle
#print axioms poll_step_has_no_self_loop
#print axioms valid_completion_binds_stable_dispatch_key
#print axioms valid_completion_is_generation_independent
#print axioms terminal_completion_during_replacement_wins
#print axioms terminal_completion_prevents_replay_even_after_binding
#print axioms orphaned_dispatch_without_binding_waits
#print axioms orphaned_dispatch_after_binding_replays_stable_key
