import ASPProof.AgentSessionHostRegistrySemanticAbstractionDiscriminatorConformance

open ASPProof.AgentSessionHostRegistrySemanticAbstractionDiscriminatorConformance

#print axioms adequate_abstraction_reflects_observational_equivalence
#print axioms observational_equivalence_binds_all_relevant_fields
#print axioms constant_abstraction_is_not_adequate
#print axioms injective_encoding_reflects_semantic_equality
#print axioms constant_encoding_is_not_injective
#print axioms every_reference_discriminator_is_total
#print axioms conforming_discriminator_binds_artifact
#print axioms conforming_discriminator_binds_input
#print axioms conforming_discriminator_requires_exit_zero
#print axioms conforming_discriminator_matches_reference_decision
#print axioms conforming_replay_binds_artifact_input_output
#print axioms conforming_replay_matches_decision
#print axioms conforming_replay_uses_independent_executor
#print axioms conforming_replay_is_marked_replayed
#print axioms artifact_drift_rejects_discriminator
#print axioms input_drift_rejects_discriminator
#print axioms reference_mismatch_rejects_discriminator
#print axioms same_executor_rejects_discriminator_replay
#print axioms response_drift_rejects_discriminator_replay
#print axioms exit_zero_only_evidence_is_constructible
#print axioms always_prefer_accepted_disagrees_with_equivalent_reference
