import ASPProof.AgentSessionLifecycleSpawnObservationGap

open ASPProof.AgentSessionLifecycleSpawnObservationGap

#print axioms preSpawnAndGapHaveSameCallerProjection
#print axioms preSpawnAndGapHaveDifferentHostOwnership
#print axioms callerObservationDoesNotDetermineHostOwnership
#print axioms postSpawnActivityAloneDoesNotAdmitBinding
#print axioms canonicalTaskNameDoesNotProveTypedRole
#print axioms defaultFullHistoryDoesNotAdmitConfiguredResident
#print axioms closedChainHasDurablePreSpawnAuthority
#print axioms closedChainHasIndexedPostSpawnEvidence
#print axioms digestIdentityDoesNotProveExecutableClosure
#print axioms executableClosureDoesNotProveSemanticAdmission
#print axioms unrelatedProviderFailurePreservesReadyRoute
#print axioms globalConjunctionMasksAReadyRoute
#print axioms registryRetirementAloneDoesNotProveHostPathRelease
#print axioms retiredPhysicalGenerationCannotBeReadopted
#print axioms admittedReplacementStrictlyAdvancesGeneration
