import ASPProof.ASPAgentSessionFencing

open ASPProof.ASPAgentSessionFencing

#print axioms staleSessionEpochRejectsCompletion
#print axioms staleAgentGenerationRejectsCompletion
#print axioms staleTurnTokenRejectsCompletion
#print axioms currentFencedCompletionIsAdmissible
#print axioms drainingRejectsExternalCommand
#print axioms staleObservationCannotBecomeAuthority
#print axioms currentObservationMatchesAuthority
#print axioms enqueueMessageOnceIsIdempotent
#print axioms consumeReceiptOnceIsIdempotent
