import ASPProof.ASPAgentLifeSessionClose

open ASPProof.ASPAgentLifeSessionClose

#print axioms archiveIsPresentationOnly
#print axioms archiveDoesNotAuthorizeReplacement
#print axioms closeIntentPersistsStableDispatchKey
#print axioms persistedCloseEdgeDoesNotProveTermination
#print axioms staleRevisionIsRejected
#print axioms staleGenerationIsRejected
#print axioms mismatchedDispatchKeyIsRejected
#print axioms shutdownDispatchRequiresDurableIntent
#print axioms closeIntentAdvancesToShutdown
#print axioms timeoutBlocksWithoutAuthorizingReplacement
#print axioms lateTerminationRecoversBlockedClose
#print axioms releaseBeforeTerminationIsRejected
#print axioms terminationReceiptAdvancesClose
#print axioms releaseClosesCanonicalPath
#print axioms replacementRequiresFreshPhysicalGeneration
#print axioms archiveMayFollowCloseIntent
#print axioms duplicateCloseIntentIsIdempotent
