import ASPProof.ASPAgentLifeSessionRefinement

open ASPProof.ASPAgentLifeSessionRefinement

#print axioms staticProjectionDoesNotConferDurableAuthority
#print axioms absentBindingSelectsInternalRegistration
#print axioms orphanedBindingRemainsHostOnly
#print axioms deliveredCurrentBindingHasDurableAuthority
#print axioms staleProfileEvidenceWithholdsDurableAuthority
#print axioms invalidRunningAbsentStateFailsClosed
#print axioms legacyPortalQueuesWithoutDurableBinding
#print axioms runtimeHealthCannotCreateSessionAuthority
#print axioms runtimeGenerationCannotAlterDecision
#print axioms profileEvidenceCannotAlterNameProjection
#print axioms wrongExportStillDominatesLifeSessionAuthority
#print axioms publicSurfaceContainsOnlyThePortal
#print axioms publicCommandIsNotAnAdministrativeDirective
#print axioms hostAckAdvancesBeyondProbe
#print axioms hostAckDoesNotConferDeliveredBinding
#print axioms duplicateHostAckIsIdempotent
#print axioms rebindIntentMustPrecedeReceipt
#print axioms persistedIntentAdvancesToReceiptRequirement
#print axioms indexedReceiptClosesRebind
#print axioms completedRebindHasEveryDurableEdge
#print axioms canonicalSuccessfulRepairHasThreeTransitions
#print axioms correctedRepairKeepsOneAgentRound
#print axioms correctedRepairHasBoundedInternalProgress
#print axioms correctedRepairStrictlyReducesObservedAgentRounds
