import ASPProof.ASPAgentFacingSearchWallBudget

#print axioms ASPProof.ASPAgentFacingSearchWallBudget.subsecond_is_admitted
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.one_second_is_rejected
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.three_seconds_is_rejected
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.observed_ten_point_three_seconds_is_rejected
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.evidence_correctness_does_not_override_wall_budget
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.runtime_wait_keeps_reply_reserve
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.runtime_wait_boundary_is_not_admitted
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.supervisor_last_millisecond_is_admitted
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.supervisor_boundary_is_not_admitted
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.strict_stage_maxima_leave_wall_slack
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.shared_nine_hundred_millisecond_boundary_is_rejected
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.fast_stale_evidence_is_rejected
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.late_current_evidence_is_rejected
#print axioms ASPProof.ASPAgentFacingSearchWallBudget.overall_evidence_requires_wall_and_semantic_admission
