import ASPProof.ASPAgentSessionRegistryAuthority

#print axioms ASPProof.ASPAgentSessionRegistryAuthority.normalServerIpcIsAdmitted
#print axioms ASPProof.ASPAgentSessionRegistryAuthority.normalServerOwnerRejectsDirectFile
#print axioms ASPProof.ASPAgentSessionRegistryAuthority.serverLockRejectsDirectFile
#print axioms ASPProof.ASPAgentSessionRegistryAuthority.offlineDirectFileRequiresCliOwnership
#print axioms ASPProof.ASPAgentSessionRegistryAuthority.restartPreservesSessionAuthority
#print axioms ASPProof.ASPAgentSessionRegistryAuthority.registryLockFailureCannotAuthorizeReplacement
#print axioms ASPProof.ASPAgentSessionRegistryAuthority.registryLockFailureCannotReserveSameName
