-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.ASPInteractiveSearchLatency

open ASPProof.ASPInteractiveSearchLatency

#print axioms fortySecondForegroundWaitRejected
#print axioms everyGenerationStateReturnsProtocolReply
#print axioms evidenceRequiresCurrentGeneration
#print axioms missingGenerationReturnsNotReady
#print axioms buildingGenerationReturnsNotReady
#print axioms staleGenerationReturnsNotReady
#print axioms terminalFailureReturnsFailed
#print axioms providerRpcForbiddenFromReadyTrace
#print axioms workspaceScanForbiddenFromReadyTrace
#print axioms generationMutationForbiddenFromReadyTrace
#print axioms clientRetryForbiddenFromReadyTrace
#print axioms content_generation_requires_exact_lane_identity
#print axioms admitted_python_calibration_owns_no_production_generation
#print axioms content_generation_admission_does_not_require_an_accelerator
#print axioms base_publication_cannot_wait_for_semantic_enrichment
#print axioms failed_durability_cannot_revoke_resident_generation
#print axioms stale_durability_cannot_replace_generation
#print axioms admitted_base_generation_is_subsecond
#print axioms accelerator_requires_exact_content_identity_and_rg_equivalence
#print axioms accelerator_content_drift_fails_closed
#print axioms every_accelerated_ready_lane_is_resident
#print axioms python_graph_rpc_is_not_a_ready_lane
#print axioms ripgrep_process_is_not_a_ready_lane
#print axioms complete_absence_requires_every_candidate_verified
#print axioms unrelated_language_is_lazy
#print axioms lsp_failure_modes_are_rejected
#print axioms providerCannotOwnSearchPlan
#print axioms clientCannotOwnGeneration
#print axioms httpAdapterCannotOwnCache
#print axioms grpcAdapterCannotOwnTerminal
#print axioms directLegacyRouteExposesProductionImpact
#print axioms transitiveFeatureAndReexportExposeLegacyImpact
#print axioms disabledLegacyFeatureDoesNotCreateReachability
#print axioms legacyInventoryRowBreaksHardCut
#print axioms legacyAuthorityIngressBreaksImpactClosure
#print axioms transportAblationPreservesSemanticReceipt
#print axioms formalQualificationCannotBypassRuntimeAdmission
#print axioms languageFacadeCannotBypassRuntimeAdmission
#print axioms healthyEndpointBeforeTransactionCommitIsNotReady
#print axioms healthyBoundTransactionIsReady
#print axioms oneReadyTerminalIsExactlyOne
#print axioms cancelledWithDiagnosticIsExactlyOneTerminal
#print axioms bareCancelledTerminalRejected
#print axioms errorLabelledCancellationRejected
#print axioms duplicateTerminalRejected
#print axioms referenceReadySegmentsFitHardCeiling
#print axioms oldTenMillisecondWarmSearchBudgetRejected
#print axioms backgroundDeadlineCannotReplaceFirstReceiptBudget
