import ASPProof.ASPInteractiveSearchLatency

open ASPProof.ASPInteractiveSearchLatency

#print axioms fortySecondForegroundWaitRejected
#print axioms everyGenerationStateReturnsProtocolReply
#print axioms evidenceRequiresCurrentGeneration
#print axioms missingGenerationReturnsNotReady
#print axioms buildingGenerationReturnsNotReady
#print axioms staleGenerationReturnsNotReady
#print axioms terminalFailureReturnsFailed
#print axioms providerRpcForbiddenFromReadyTrace
#print axioms workspaceScanForbiddenFromReadyTrace
#print axioms generationMutationForbiddenFromReadyTrace
#print axioms clientRetryForbiddenFromReadyTrace
#print axioms providerCannotOwnSearchPlan
#print axioms clientCannotOwnGeneration
#print axioms httpAdapterCannotOwnCache
#print axioms grpcAdapterCannotOwnTerminal
#print axioms directLegacyRouteExposesProductionImpact
#print axioms transitiveFeatureAndReexportExposeLegacyImpact
#print axioms disabledLegacyFeatureDoesNotCreateReachability
#print axioms legacyInventoryRowBreaksHardCut
#print axioms legacyAuthorityIngressBreaksImpactClosure
#print axioms transportAblationPreservesSemanticReceipt
#print axioms oneReadyTerminalIsExactlyOne
#print axioms duplicateTerminalRejected
#print axioms referenceReadySegmentsFitHardCeiling
#print axioms oldTenMillisecondWarmSearchBudgetRejected
#print axioms backgroundDeadlineCannotReplaceFirstReceiptBudget
