import ASPProof.CodexMultiAgentV2RegistryMaterialization

open ASPProof.CodexMultiAgentV2RegistryMaterialization

#check missingScopedRootTaskEvidenceRejects
#check registryMaterializationPreservesRootTaskIdentity
#check registryFactsMintNoTurns
#check registryFactsMintNoDelegations
#check registryMaterializationPreservesOnlyAgentFacts
#check registryControlPlaneDoesNotExecuteCodex
