import ASPProof.HookEnforcementKernel

#check ASPProof.HookEnforcementKernel.control_plane_unavailability_cannot_change_decision
#check ASPProof.HookEnforcementKernel.live_and_doctor_replay_are_equivalent
#check ASPProof.HookEnforcementKernel.last_known_good_deny_is_preserved
#check ASPProof.HookEnforcementKernel.missing_snapshot_denies_unknown_source_like
#check ASPProof.HookEnforcementKernel.missing_snapshot_denies_source_materialization
#check ASPProof.HookEnforcementKernel.incomplete_provider_projection_cannot_be_admitted
#check ASPProof.HookEnforcementKernel.synchronous_control_plane_dependency_cannot_be_admitted
#check ASPProof.HookEnforcementKernel.atomic_pointer_observes_whole_generation
#check ASPProof.HookEnforcementKernel.coupled_control_plane_has_fail_open_counterexample
