-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.HookMatcherPublicationSeparation

namespace ASPProof.Audit.HookMatcherPublicationSeparation

open ASPProof.HookMatcherPublicationSeparation

#check missing_runtime_hook_binary_terminates_unavailable
#check atomic_runtime_hook_switch_exposes_one_complete_bundle
#check atomic_runtime_hook_switch_keeps_policy_and_lifecycle_on_one_binary
#check policy_and_lifecycle_share_one_hook_binary
#check config_source_edit_preserves_runtime_hook_binary
#check candidate_stage_failure_preserves_previous
#check runtime_hook_install_is_runtime_server_independent
#check evaluation_preserves_runtime_hook_binary
#check installation_makes_runtime_hook_binary_executable
#check coupled_evaluation_publication_has_self_wait_counterexample
#check separated_evaluation_cannot_self_wait
#check concurrent_readers_preserve_cardinality
#check only_standalone_hook_accepts_host_events
#check hook_configuration_does_not_capture_ordinary_cli
#check disabled_hook_engine_passes_through_before_evaluation
#check enabled_hook_engine_evaluates
#check environment_cannot_change_hook_engine_policy
#check typed_target_dispatch_is_a_fixed_point
#check registry_projection_preserves_configured_agent_kind
#check configured_testing_target_does_not_redispatch
#check hook_event_plane_constructs_no_runtime
#check stale_sibling_policy_identity_preserves_current
#check healthy_observation_cannot_change_active_hook_authority
#check install_switches_only_active
#check ready_candidate_moves_only_healthy
#check failed_current_candidate_restores_active_from_healthy
#check stale_candidate_cannot_commit_or_rollback
#check launcher_reads_active_not_healthy
#check legacy_hook_selector_cannot_override_runtime_bin

end ASPProof.Audit.HookMatcherPublicationSeparation
