import ASPProof.HookMatcherPublicationSeparation

namespace ASPProof.Audit.HookMatcherPublicationSeparation

open ASPProof.HookMatcherPublicationSeparation

#check missing_generation_terminates_unavailable
#check atomic_switch_exposes_one_complete_generation
#check atomic_switch_keeps_policy_and_lifecycle_on_one_generation
#check policy_and_lifecycle_share_one_hook_binary
#check config_source_edit_preserves_active_generation
#check candidate_stage_failure_preserves_previous
#check hook_commit_is_runtime_independent
#check evaluation_preserves_generation
#check publication_makes_generation_readable
#check coupled_evaluation_publication_has_self_wait_counterexample
#check separated_evaluation_cannot_self_wait
#check concurrent_readers_preserve_cardinality
#check legacy_deadlock_cycle_is_reachable
#check process_environment_override_makes_deadlock_unreachable
#check launcher_environment_override_makes_deadlock_unreachable
#check direct_assignment_is_recovery_authority
#check env_utility_assignment_is_recovery_authority
#check export_exec_assignment_is_recovery_authority
#check unbound_payload_text_is_not_recovery_authority
#check export_exec_escape_survives_missing_generation
#check unbound_text_cannot_escape_missing_generation
#check command_environment_override_makes_deadlock_unreachable
#check recovery_override_does_not_capture_ordinary_cli
#check recovery_override_precedes_policy_for_hook_event
#check typed_target_dispatch_is_a_fixed_point
#check policy_data_plane_precedes_runtime_and_lifecycle_is_not_single_worker

end ASPProof.Audit.HookMatcherPublicationSeparation
