import ASPProof.HookRecoveryDeadlockFreedom

namespace ASPProof.Audit.HookRecoveryDeadlockFreedom

#check ASPProof.HookRecoveryDeadlockFreedom.recovery_override_dominates_every_state
#check ASPProof.HookRecoveryDeadlockFreedom.target_identity_is_dispatch_fixed_point
#check ASPProof.HookRecoveryDeadlockFreedom.non_target_denial_requires_one_dispatch
#check ASPProof.HookRecoveryDeadlockFreedom.legacy_dispatch_recurses_inside_target
#check ASPProof.HookRecoveryDeadlockFreedom.recovery_override_has_no_stateful_dependency
#check ASPProof.HookRecoveryDeadlockFreedom.legacy_broken_binary_recursive_deny_is_deadlocked
#check ASPProof.HookRecoveryDeadlockFreedom.recovery_override_breaks_recursive_repair_deadlock
#check ASPProof.HookRecoveryDeadlockFreedom.legacy_v1_stale_does_not_assert_runtime_health
#check ASPProof.HookRecoveryDeadlockFreedom.malformed_receipt_does_not_assert_runtime_health
#check ASPProof.HookRecoveryDeadlockFreedom.runtime_authority_cannot_change_process_recovery
#check ASPProof.HookRecoveryDeadlockFreedom.process_recovery_is_reachable_from_every_runtime_state
#check ASPProof.HookRecoveryDeadlockFreedom.normal_mode_cannot_consume_recovery_authority
#check ASPProof.HookRecoveryDeadlockFreedom.validated_candidate_restores_normal_runtime_authority
#check ASPProof.HookRecoveryDeadlockFreedom.recovery_step_strictly_advances
#check ASPProof.HookRecoveryDeadlockFreedom.recovery_transition_is_acyclic
#check ASPProof.HookRecoveryDeadlockFreedom.lexical_alias_can_miss_raw_authority
#check ASPProof.HookRecoveryDeadlockFreedom.normalized_aliases_share_authority
#check ASPProof.HookRecoveryDeadlockFreedom.last_admitted_microsecond_is_within_budget
#check ASPProof.HookRecoveryDeadlockFreedom.one_millisecond_is_rejected
#check ASPProof.HookRecoveryDeadlockFreedom.scheduler_preemption_refutes_universal_wall_max
#check ASPProof.HookRecoveryDeadlockFreedom.five_hundred_microseconds_meets_typical_target
#check ASPProof.HookRecoveryDeadlockFreedom.eight_hundred_twenty_three_is_admitted_but_not_safe_headroom
#check ASPProof.HookRecoveryDeadlockFreedom.twenty_four_of_thirty_two_has_typical_quorum
#check ASPProof.HookRecoveryDeadlockFreedom.twenty_three_of_thirty_two_lacks_typical_quorum
#check ASPProof.HookRecoveryDeadlockFreedom.concurrent_readers_cannot_change_decision
#check ASPProof.HookRecoveryDeadlockFreedom.serialized_reader_queue_violates_budget
#check ASPProof.HookRecoveryDeadlockFreedom.lock_free_reader_latency_is_concurrency_invariant
#check ASPProof.HookRecoveryDeadlockFreedom.lock_free_reader_preserves_budget
#check ASPProof.HookRecoveryDeadlockFreedom.atomic_publication_never_exposes_torn_generation

end ASPProof.Audit.HookRecoveryDeadlockFreedom
