import ASPProof.HookSourceAccessReplayIdentity

#check ASPProof.HookSourceAccessReplayIdentity.freeformEnvelopePreservesNestedAction
#check ASPProof.HookSourceAccessReplayIdentity.distinctOwnerCannotCollapseReplayLane
#check ASPProof.HookSourceAccessReplayIdentity.distinctLanguageCannotCollapseReplayLane
#check ASPProof.HookSourceAccessReplayIdentity.replayPreservesExecutableRoute
#check ASPProof.HookSourceAccessReplayIdentity.replayPreservesNaturalLanguage
