-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.LiveCorpusPredicateRoute

open ASPProof.LiveCorpusPredicateRoute

#print axioms primary_route_never_requires_a_partner
#print axioms every_intent_has_one_primary_route
#print axioms conjunction_requires_both_complete_witnesses
#print axioms conjunction_requires_one_generation
#print axioms conjunction_requires_one_owner_universe
#print axioms overlapping_engines_without_explicit_conjunction_are_rejected
#print axioms truncated_left_input_cannot_prove_intersection
#print axioms truncated_right_input_cannot_prove_intersection
#print axioms different_generations_cannot_prove_intersection
#print axioms different_owner_universes_cannot_prove_intersection
#print axioms ranked_top_k_cannot_prove_set_intersection
