import ASPProof.MultiAgentChoicePlane
import ASPProof.MultiAgentResidentNamespace
import ASPProof.MultiAgentProviderFacadeAuthority

open ASPProof.MultiAgentChoicePlane
open ASPProof.MultiAgentResidentNamespace
open ASPProof.MultiAgentProviderFacadeAuthority

#print axioms applicability_model_allows_multiple_current_choices
#print axioms current_contract_admission_is_sound_and_complete
#print axioms missing_resident_exposes_creation_without_speculative_resume
#print axioms mismatched_resident_exposes_archive_before_replacement
#print axioms archived_resident_exposes_only_new_generation_creation
#print axioms registered_implies_exact_live_binding
#print axioms registered_node_implies_exact_live_binding
#print axioms same_name_spoof_cannot_register
#print axioms wrong_child_cannot_register
#print axioms wrong_root_cannot_register
#print axioms wrong_instance_cannot_register
#print axioms wrong_registration_cannot_register
#print axioms wrong_resident_id_cannot_register
#print axioms wrong_route_cannot_register
#print axioms wrong_generation_cannot_register
#print axioms wrong_profile_cannot_register
#print axioms wrong_model_cannot_register
#print axioms wrong_sandbox_cannot_register
#print axioms completed_cannot_register
#print axioms stopped_cannot_register
#print axioms unregistered_cannot_register
#print axioms archived_cannot_register
#print axioms resume_preserves_exact_live_identity
#print axioms recreation_requires_new_instance_registration_and_higher_generation
#print axioms terminal_binding_cannot_be_reused
#print axioms missing_resident_cannot_form_archive_request
#print axioms archive_request_carries_the_identified_resident
#print axioms recreate_requires_distinct_identity_and_higher_generation
#print axioms reentry_uses_current_observation_without_replaying_history
#print axioms host_choice_request_carries_no_runtime_state_mutation
#print axioms current_disclosure_is_exactly_sufficient
#print axioms progressive_disclosure_withholds_future_state_facts
#print axioms every_choice_discloses_the_configured_sandbox
#print axioms reasoning_projection_names_a_typed_postcondition
#print axioms non_progress_consumes_the_finite_budget
#print axioms exhausted_non_progress_cannot_retry
#print axioms exhausted_loop_without_verified_defect_is_typed_blocked
#print axioms pass_through_requires_a_verified_invariant_defect
#print axioms pass_through_cannot_be_reused
#print axioms naked_pass_through_request_is_never_authority
#print axioms command_binding_drift_fails_closed
#print axioms agent_facing_lifecycle_surface_is_singleton
#print axioms configured_resident_ids_are_exact
#print axioms configured_resident_ids_are_unique
#print axioms root_namespace_has_one_slot_per_configured_resident
#print axioms matching_live_resident_is_always_resumed
#print axioms matching_live_resident_cannot_create_temporary
#print axioms absent_resident_without_temporary_authority_creates_resident
#print axioms temporary_without_explicit_authority_cannot_be_created
#print axioms valid_explicit_temporary_authority_is_required_and_sufficient
#print axioms nonmatched_work_never_acquires_asp_resident_authority
#print axioms every_registered_provider_binary_is_denied_in_bound_session
#print axioms missing_child_binding_fails_closed_for_direct_provider_execution
#print axioms registered_language_facade_is_authorized_independently_of_language
#print axioms unregistered_binary_is_not_misclassified_as_provider_internal
