-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.MultiAgentLifeSession

open ASPProof.MultiAgentLifeSession

#print axioms unverifiedBindingCannotAuthorizeDispatch
#print axioms wrongSessionNameCannotAuthorizeDispatch
#print axioms wrongPlatformTargetCannotAuthorizeDispatch
#print axioms exactCodexHookExecutorCannotRouteToItself
#print axioms partialCodexHookExecutorCannotProveResidentIdentity
#print axioms wellFormedResidentSlotHasAtMostOneLiveGeneration
#print axioms installedTestingResidentResolvesByConfiguredRouteKey
#print axioms installedTestingResidentPreservesExplorerRoute
#print axioms temporaryAgentsDoNotConsumeResidentSlots
#print axioms unit_verification_never_owns_the_host_supervisor
#print axioms installation_smoke_cannot_replace_local_policy_evaluation
#print axioms local_hook_process_owns_policy_evaluation
#print axioms runtime_state_api_cannot_evaluate_hook_policy
#print axioms only_platform_profile_name_defines_agent_identity
#print axioms hook_config_overlay_cannot_shadow_agent_identity
#print axioms rust_literal_cannot_shadow_agent_identity
#print axioms registered_session_preserves_configured_lifetime
#print axioms unregistered_session_cannot_inherit_resident_lifetime
#print axioms lifecycle_action_preserves_registry_platform_identity
#print axioms codex_session_and_thread_identify_the_same_host
#print axioms hook_route_controls_registered_role_and_description
#print axioms cli_invocation_cannot_override_hook_selected_route
#print axioms process_environment_cannot_override_hook_route_root
#print axioms only_runtime_server_resolves_session_scope
#print axioms missing_projected_child_uses_workspace_identity
#print axioms session_lookup_uses_only_runtime_status_memory
#print axioms only_runtime_server_publishes_session_projection
#print axioms runtime_session_projection_excludes_choice_plan_fields
#print axioms only_org_interactive_contract_defines_choice_plan
#print axioms command_layer_is_only_a_cli_and_host_context_adapter
#print axioms registration_requires_a_host_lifecycle_event
#print axioms missing_root_and_unverified_parent_chain_cannot_authorize_registration
#print axioms direct_parent_edge_authorizes_missing_redundant_root
#print axioms root_identity_mismatch_cannot_authorize_registration
#print axioms nested_parent_is_distinct_from_root_and_still_verifies
#print axioms environment_thread_is_optional_and_not_child_authority
#print axioms verified_nested_parent_chain_authorizes_missing_redundant_root
#print axioms creation_choice_uses_the_host_native_register_action
#print axioms stale_and_archived_generations_use_distinct_host_actions
#print axioms only_runtime_server_records_host_lifecycle_events
#print axioms changed_model_requires_archive_before_replacement
#print axioms registered_resident_pane_returns_direct_call_resume
#print axioms registered_presentation_is_contract_owned_direct_action
#print axioms missing_registration_offers_only_creation
#print axioms missing_registration_presentations_are_contract_owned_panes
#print axioms expired_or_invalid_generation_requires_archive_before_replacement
#print axioms archive_required_presentation_is_a_contract_owned_action
#print axioms archived_generation_cannot_resume_and_creates_a_new_generation
#print axioms archived_presentation_is_a_contract_owned_action
#print axioms unavailable_authority_never_falls_back_to_agent_creation
#print axioms unavailable_authority_presentation_is_a_contract_owned_pane
