import ASPProof.MultiAgentChoicePlane

open ASPProof.MultiAgentChoicePlane

#print axioms applicability_model_allows_multiple_current_choices
#print axioms current_contract_admission_is_sound_and_complete
#print axioms missing_resident_exposes_creation_without_speculative_resume
#print axioms mismatched_resident_exposes_archive_before_replacement
#print axioms archived_resident_exposes_only_new_generation_creation
#print axioms missing_resident_cannot_form_archive_request
#print axioms archive_request_carries_the_identified_resident
#print axioms recreate_requires_distinct_identity_and_higher_generation
#print axioms reentry_uses_current_observation_without_replaying_history
#print axioms host_choice_request_carries_no_runtime_state_mutation
#print axioms current_disclosure_is_exactly_sufficient
#print axioms progressive_disclosure_withholds_future_state_facts
#print axioms reasoning_projection_names_a_typed_postcondition
#print axioms non_progress_consumes_the_finite_budget
#print axioms exhausted_non_progress_cannot_retry
#print axioms exhausted_loop_without_verified_defect_is_typed_blocked
#print axioms pass_through_requires_a_verified_invariant_defect
#print axioms pass_through_cannot_be_reused
#print axioms naked_pass_through_request_is_never_authority
#print axioms command_binding_drift_fails_closed
#print axioms agent_facing_lifecycle_surface_is_singleton
