import ASPProof.NoncancellableColdGenerationAdmission

open ASPProof.NoncancellableColdGenerationAdmission

#check timeoutCannotCancelQueuedRepair
#check timeoutAfterAdmissionIsNotMissing
#check queuedRepairPublishesReady
#check timeoutDoesNotAuthorizeUnpublishedRead
#check residentReadyNeverEnqueuesRepair
#check residentReadyStaysInsideHundredMillisecondBudget
#check residentReadyPerformsNoProviderOrDatabaseWork
#check onlyServerBootstrapOwnsDurableRepair
#check explicitQueryReleasesIffTerminalReady
#check buildingAdmissionCannotEnterOwnerFreshness
#check failedAdmissionCannotEnterOwnerFreshness
#check terminalReadyPrecedesOwnerFreshness
#check admissionReadyWithoutPublishedLeaseCannotRelease
#check residentReadyAndPointerExistsWithoutCurrentSchemaCannotRelease
#check currentSchemaPointerForAnotherGenerationCannotRelease
#check publishedTerminalReadinessCanRelease
