import ASPProof.NoncancellableColdGenerationAdmission

open ASPProof.NoncancellableColdGenerationAdmission

#check timeoutCannotCancelQueuedRepair
#check timeoutAfterAdmissionIsNotMissing
#check queuedRepairPublishesReady
#check timeoutDoesNotAuthorizeUnpublishedRead
