import ASPProof.OrgizeTypstLintEvidence

namespace ASPProof.Audit.OrgizeTypstLintEvidence

#print axioms ASPProof.OrgizeTypstLintEvidence.structural_valid_implies_proof_lane
#print axioms ASPProof.OrgizeTypstLintEvidence.exact_binding_preserves_program
#print axioms ASPProof.OrgizeTypstLintEvidence.runtime_valid_requires_schema_version
#print axioms ASPProof.OrgizeTypstLintEvidence.runtime_valid_requires_exited
#print axioms ASPProof.OrgizeTypstLintEvidence.runtime_valid_requires_exit_zero
#print axioms ASPProof.OrgizeTypstLintEvidence.runtime_valid_requires_reaped
#print axioms ASPProof.OrgizeTypstLintEvidence.runtime_valid_requires_exact_context
#print axioms ASPProof.OrgizeTypstLintEvidence.runtime_valid_requires_package_root
#print axioms ASPProof.OrgizeTypstLintEvidence.runtime_valid_requires_combined_budget
#print axioms ASPProof.OrgizeTypstLintEvidence.runtime_valid_requires_accepted_status
#print axioms ASPProof.OrgizeTypstLintEvidence.acceptance_preserved_by_valid_receipts
#print axioms ASPProof.OrgizeTypstLintEvidence.acceptance_requires_structural_evidence
#print axioms ASPProof.OrgizeTypstLintEvidence.acceptance_requires_runtime_evidence
#print axioms ASPProof.OrgizeTypstLintEvidence.missing_runtime_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.missing_structural_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.wrong_runtime_binding_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.missing_package_root_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.mismatched_package_root_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.zero_timeout_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.zero_output_budget_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.output_budget_exceeded_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.elapsed_timeout_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.timed_out_outcome_rejected
#print axioms ASPProof.OrgizeTypstLintEvidence.output_budget_exceeded_outcome_rejected
#print axioms ASPProof.OrgizeTypstLintEvidence.spawn_failed_outcome_rejected
#print axioms ASPProof.OrgizeTypstLintEvidence.io_failed_outcome_rejected
#print axioms ASPProof.OrgizeTypstLintEvidence.exited_without_exit_code_rejected
#print axioms ASPProof.OrgizeTypstLintEvidence.nonzero_exit_rejected
#print axioms ASPProof.OrgizeTypstLintEvidence.unreaped_child_rejected
#print axioms ASPProof.OrgizeTypstLintEvidence.rejected_status_rejected
#print axioms ASPProof.OrgizeTypstLintEvidence.accepted_status_cannot_launder_failure_outcome
#print axioms ASPProof.OrgizeTypstLintEvidence.zero_exit_cannot_launder_rejected_status
#print axioms ASPProof.OrgizeTypstLintEvidence.untyped_lint_header_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.untyped_format_header_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.untyped_runtime_header_fails_closed
#print axioms ASPProof.OrgizeTypstLintEvidence.structural_success_counterexample
#print axioms ASPProof.OrgizeTypstLintEvidence.structural_success_does_not_imply_runtime_validity
#print axioms ASPProof.OrgizeTypstLintEvidence.structural_evidence_cannot_be_laundered_as_acceptance

end ASPProof.Audit.OrgizeTypstLintEvidence
