import ASPProof.PolyglotSearchArtifactReplay

namespace ASPProof.Audit.PolyglotSearchArtifactReplay

#print axioms ASPProof.PolyglotSearchArtifactReplay.fixture_graph_is_read_only
#print axioms ASPProof.PolyglotSearchArtifactReplay.fixture_gql_rows_replay_reference_semantics
#print axioms ASPProof.PolyglotSearchArtifactReplay.fixture_logic_rows_replay_reference_semantics
#print axioms ASPProof.PolyglotSearchArtifactReplay.fixture_gql_bag_has_three_rows
#print axioms ASPProof.PolyglotSearchArtifactReplay.fixture_gql_bag_preserves_parallel_witnesses
#print axioms ASPProof.PolyglotSearchArtifactReplay.fixture_logic_bag_has_three_rows
#print axioms ASPProof.PolyglotSearchArtifactReplay.fixture_logic_bag_preserves_parallel_witnesses
#print axioms ASPProof.PolyglotSearchArtifactReplay.fixture_policy_is_canonical
#print axioms ASPProof.PolyglotSearchArtifactReplay.committed_artifact_replay_is_admitted
#print axioms ASPProof.PolyglotSearchArtifactReplay.payload_tampering_is_rejected

end ASPProof.Audit.PolyglotSearchArtifactReplay
