-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.ResidentGrepCost

#check ASPProof.ResidentGrepCost.ready_phase_keeps_resident_budget
#check ASPProof.ResidentGrepCost.first_phase_is_monotone

namespace ASPProof.Audit.ResidentGrepCost

open ASPProof.ResidentGrepCost

#check exact_hits_subset_candidates
#check exact_verification_of_sound_candidates_is_complete
#check mandatory_subset_retains_candidate_soundness
#check more_mandatory_grams_never_widen
#check empty_candidates_imply_no_exact_hits
#check candidate_scope_pushdown_preserves_hits
#check exact_rg_owner_scope_pushdown_preserves_fusion
#check not_materialized_cannot_publish_absence
#check complete_fused_scope_empty_implies_absence
#check externally_pure_has_no_binary_or_filesystem_work
#check prefix_decode_bounded_by_full_decode
#check fixed_cost_blocks_target_factor
#check limit_before_intersection_loses_hit
#check v1_directory_field_accounting
#check mapped_generation_has_zero_workspace_heap_retention
#check flat_posting_arena_never_exceeds_fragmented
#check fragmented_arena_overhead_is_per_gram
#check admitted_tokio_lane_preserves_reactor
#check cached_digest_check_equivalent
#check owner_hash_work_decomposition
#check owner_hash_reuse_never_increases_byte_work
#check offloaded_assembly_has_no_reactor_work
#check changed_source_rejects_recovery
#check same_lane_does_not_prove_freshness
#check zero_io_without_continuity_cannot_admit
#check current_snapshot_admission_observes_workspace
#check uninterrupted_continuity_admits_zero_io
#check changed_execution_rejects_recovery
#check changed_scope_rejects_recovery
#check publication_retains_terminal_for_late_waiters
#check waiter_cancellation_preserves_shared_terminal
#check first_search_work_excludes_attachments
#check split_critical_path_never_adds_work
#check source_acquisition_has_byte_lower_bound
#check generation_rebind_preserves_parser_artifact
#check changed_owner_content_rejects_parser_artifact
#check unrelated_auxiliary_is_outside_owner_cut
#check applicable_auxiliary_enters_owner_cut
#check failed_durability_preserves_resident_read
#check resident_is_not_restart_restorable
#check candidate_projection_work_is_bounded
#check parser_cache_hit_has_zero_provider_starts
#check provider_group_batch_never_exceeds_serial_owner_rpc
#check one_generation_barrier_removes_duplicate_inventory
#check v1_digest_boundary_translation_preserves_content
#check exact_owner_replay_has_no_provider_generation_or_async_cpu_work
#check exact_owner_replay_is_one_resource_owned_blocking_pipeline
#check exact_owner_replay_preflight_copies_no_owner_snapshot
#check four_thread_runtime_reserves_one_worker_from_background_cpu
#check process_cold_exact_replay_never_publishes_workspace_ready
#check changed_owner_rejects_process_cold_exact_replay
#check changed_runtime_bundle_rejects_process_cold_exact_replay
#check relocation_rejects_process_cold_exact_replay
#check request_graph_work_is_candidate_bounded
#check resident_semantic_publication_excludes_workspace_rewrite
#check delta_only_overlay_work_equals_delta
#check copying_base_bytes_adds_forbidden_work
#check admitted_search_plane_has_zero_request_workspace_build
#check read_handle_reference_work_is_independent_of_workspace
#check rebuilding_each_handle_multiplies_workspace_work
#check internal_byte_coverage_has_no_duplicate_full_validation
#check restored_byte_coverage_retains_full_validation
#check internal_settlement_has_no_duplicate_decode
#check external_settlement_retains_full_admission
#check ready_owner_scope_has_zero_registry_acquisitions
#check indexed_settlement_work_is_independent_of_workspace
#check full_scan_settlement_pays_workspace_node_scan
#check admitted_generation_retains_at_most_two_terminals
#check evicted_cache_slot_does_not_erase_waiter_terminal
#check exact_grounding_never_exceeds_full_owner_projection
#check lexical_ready_does_not_require_graph_terminal
#check indexed_query_work_is_independent_of_workspace
#check resident_exact_query_skips_owner_materializer
#check resident_query_projection_handoff_reads_each_selector_once
#check materialized_response_hit_does_not_certify_selector_read
#check provider_bootstrap_is_outside_runtime_data_plane
#check generic_client_language_provider_dependency_is_forbidden
#check resident_candidate_projection_has_zero_filesystem_reads
#check auxiliary_inputs_do_not_expand_search_owner_count
#check whole_owner_automaton_has_one_matcher_entrance
#check whole_owner_automaton_removes_per_line_restarts

end ASPProof.Audit.ResidentGrepCost
