-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.RuntimeBinaryProfileDispatch

namespace ASPProof.Audit.RuntimeBinaryProfileDispatch

#print axioms ASPProof.RuntimeBinaryProfileDispatch.provider_internal_admission_requires_runtime_capability
#print axioms ASPProof.RuntimeBinaryProfileDispatch.matching_live_provider_capability_is_admitted
#print axioms ASPProof.RuntimeBinaryProfileDispatch.direct_provider_internal_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.invalid_provider_capability_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_root_session_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_active_root_session_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_child_session_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_active_child_session_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_binary_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_profile_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_provider_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_language_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_generation_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_artifact_digest_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_argv_digest_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.wrong_attempt_is_replay_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.not_yet_issued_capability_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.expired_capability_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.consumed_capability_is_replay_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.test_fixture_outside_test_runtime_is_denied
#print axioms ASPProof.RuntimeBinaryProfileDispatch.facade_is_not_misclassified_as_provider_internal
#print axioms ASPProof.RuntimeBinaryProfileDispatch.unregistered_runtime_binary_fails_closed
#print axioms ASPProof.RuntimeBinaryProfileDispatch.profile_admission_is_not_a_binary_name_blacklist

end ASPProof.Audit.RuntimeBinaryProfileDispatch
