-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.RuntimeResidentLifecycle
import ASPProof.RuntimeServerLifecycle

namespace ASPProof.Audit.RuntimeResidentLifecycle

open ASPProof.RuntimeResidentLifecycle
open ASPProof.RuntimeServerLifecycle

#check matching_profile_is_ready
#check missing_typed_spawn_blocks
#check missing_retirement_blocks
#check missing_path_release_blocks
#check complete_host_capability_replaces
#check admitted_transition_decreases_rank
#check repair_never_blocks_unrelated_tools
#check same_generation_lease_owner_unique
#check zero_workspace_does_not_imply_shutdown
#check daemon_shutdown_requires_missing_or_expired_lease
#check supervisor_process_without_endpoint_not_healthy
#check missing_generation_returns_without_waiting_or_building
#check ready_generation_reads_without_provider_or_parser
#check ready_generation_cannot_escape_to_secondary_runtime
#check admitted_request_receipt_has_zero_external_work
#check admitted_request_receipt_is_strictly_submillisecond
#check deadline_boundary_receipt_is_rejected
#check secondary_runtime_receipt_is_rejected
#check failed_search_attachment_does_not_revoke_ready_query
#check failed_search_attachment_cannot_serve_search
#check cold_and_warm_requests_have_identical_resident_effects
#check stale_generation_cannot_be_revalidated_inside_request
#check request_terminal_callback_cannot_publish_resident_generation
#check explicit_ensure_ready_route_cannot_publish_resident_generation
#check daemon_execution_observer_is_the_resident_publication_authority
#check nested_mailbox_cannot_own_derived_generation_terminal
#check daemon_observer_owns_derived_generation_terminal
#check discarded_derived_generation_terminal_does_not_close
#check ready_and_failed_dispositions_close_derived_generation_terminal

end ASPProof.Audit.RuntimeResidentLifecycle
