import ASPProof.SearchArchitectureImpactReport

open ASPProof.SearchArchitectureImpactReport

#print axioms directFallbackProducesRejectedReport
#print axioms directFallbackPreservesShortestCounterexample
#print axioms orphanLegacyProviderCacheBreaksSourceHardCut
#print axioms orphanLegacyProviderCacheIsReportedEvenWhenUnreachable
#print axioms generatedClientSearchPlannerIsRejected
#print axioms generatedClientSearchPlannerReportsBothCapabilities
#print axioms legacyGraphEvaluateReadyRouteIsRejected
#print axioms legacyGraphEvaluateReadyRoutePreservesShortestCounterexample
#print axioms legacyGraphEvaluateReadyRouteReportsPythonExecutable
#print axioms proofReportNeverInventsAxioms
