-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.ServerDerivedSchemaDistribution

#print axioms ASPProof.ServerDerivedSchemaDistribution.shared_closure_is_not_package_local
#print axioms ASPProof.ServerDerivedSchemaDistribution.provider_semantics_remain_package_local
#print axioms ASPProof.ServerDerivedSchemaDistribution.server_cannot_invent_shared_schema
#print axioms ASPProof.ServerDerivedSchemaDistribution.exact_canonical_shared_schema_is_projectable
#print axioms ASPProof.ServerDerivedSchemaDistribution.registered_absent_digest_is_ready
#print axioms ASPProof.ServerDerivedSchemaDistribution.registered_current_digest_is_unchanged
#print axioms ASPProof.ServerDerivedSchemaDistribution.registered_stale_digest_is_ready
#print axioms ASPProof.ServerDerivedSchemaDistribution.unknown_language_fails_closed
#print axioms ASPProof.ServerDerivedSchemaDistribution.root_set_drift_fails_closed
#print axioms ASPProof.ServerDerivedSchemaDistribution.malformed_digest_fails_closed
#print axioms ASPProof.ServerDerivedSchemaDistribution.immutable_catalog_projection_is_schema_count_independent
#print axioms ASPProof.ServerDerivedSchemaDistribution.unchanged_transfers_no_documents
#print axioms ASPProof.ServerDerivedSchemaDistribution.ready_transfer_is_linear_in_document_count
#print axioms ASPProof.ServerDerivedSchemaDistribution.corrupted_bundle_receipt_is_rejected
#print axioms ASPProof.ServerDerivedSchemaDistribution.provider_schema_cannot_be_reclassified_as_server_projection
#print axioms ASPProof.ServerDerivedSchemaDistribution.target_removes_language_multiplier
#print axioms ASPProof.ServerDerivedSchemaDistribution.legacy_replication_never_smaller_when_language_exists
