-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.WorkspaceSearchPlaybookPlanner

open ASPProof.WorkspaceSearchPlaybookPlanner

#print axioms admitted_request_has_direct_native_axes
#print axioms clause_kinds_are_pairwise_distinct
#print axioms native_argument_is_forwarded_unchanged
#print axioms standalone_shell_pipe_is_rejected
#print axioms acquisition_clause_does_not_consume_another_clause
#print axioms targeted_recovery_is_exactly_example_and_grammar
#print axioms targeted_repair_strictly_decreases_missing_axes
#print axioms no_match_requires_complete_coverage
#print axioms syntax_result_maps_to_one_exact_query
#print axioms exact_query_round_trips_to_same_parser_node
#print axioms syntax_result_selector_is_generation_current
#print axioms stale_selector_fails_closed
#print axioms snapshot_source_facts_are_not_persistable
#print axioms source_drift_invalidates_snapshot_fact
#print axioms invalid_parent_invalidates_derived_fact
#print axioms valid_derived_parent_is_current
#print axioms ascent_cannot_mint_exact_selector
#print axioms stale_warm_observation_has_zero_priority
#print axioms warm_start_cannot_prune_registered_clause_kinds
#print axioms ext_score_is_scheduling_only
#print axioms ext_schedule_preserves_semantic_result
#print axioms ext_schedule_preserves_clause_receipts
#print axioms ext_schedule_can_change_execution_order
#print axioms new_branch_requires_evidence_validation_before_quality_gate
#print axioms search_agent_handoff_contains_no_source
#print axioms selector_only_handoff_has_zero_duplicate_source_cost
#print axioms search_agent_handoff_respects_top_k
#print axioms search_agent_handoff_does_not_constrain_continuation
#print axioms every_syntax_evidence_maps_to_an_exact_query
#print axioms syntax_query_projection_does_not_constrain_continuation
#print axioms projection_contains_only_admitted_evidence
#print axioms projection_respects_top_k
#print axioms projection_respects_token_budget
#print axioms projection_preserves_required_witness
#print axioms projection_preserves_axis_diversity_when_globally_feasible
#print axioms truncated_projection_cannot_establish_complete_absence
#print axioms projection_receipt_reports_exact_selected_count
#print axioms projection_receipt_reports_exact_token_cost
#print axioms token_pressure_cannot_silently_close
#print axioms owner_without_parser_selectors_preserves_later_stages
#print axioms identity_drift_cannot_be_downgraded_to_unavailable
