//! Activation schema DTOs and resolved runtime provider routing models.

use serde::{Deserialize, Serialize};

use crate::protocol::{CommandTemplate, HookPolicy, HookRoutes};

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ProviderRuntimeContractTransport {
    RuntimeIpc,
    HttpJson,
    InProcess,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderRuntimeContractOperationDescriptor {
    pub(crate) operation: String,
    pub(crate) request_schema_id: String,
    pub(crate) response_schema_id: String,
}

impl ProviderRuntimeContractOperationDescriptor {
    pub fn operation(&self) -> &str {
        &self.operation
    }

    pub fn request_schema_id(&self) -> &str {
        &self.request_schema_id
    }

    pub fn response_schema_id(&self) -> &str {
        &self.response_schema_id
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderRuntimeContractDescriptor {
    pub(crate) transport: ProviderRuntimeContractTransport,
    pub(crate) asp_client_server: Option<AspClientServerDescriptor>,
    pub(crate) operations: Vec<ProviderRuntimeContractOperationDescriptor>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AspClientServerDescriptor {
    pub(crate) schema_id: String,
    pub(crate) schema_version: String,
    pub(crate) transport: ProviderRuntimeContractTransport,
    pub(crate) command: Vec<String>,
    pub(crate) health_path: String,
    pub(crate) request_path: String,
    pub(crate) shutdown_path: String,
    pub(crate) warmup_policy: String,
}

impl ProviderRuntimeContractDescriptor {
    pub const fn transport(&self) -> ProviderRuntimeContractTransport {
        self.transport
    }

    pub fn operations(&self) -> &[ProviderRuntimeContractOperationDescriptor] {
        &self.operations
    }

    pub fn asp_client_server(&self) -> Option<&AspClientServerDescriptor> {
        self.asp_client_server.as_ref()
    }
}

impl AspClientServerDescriptor {
    pub fn command(&self) -> &[String] {
        &self.command
    }

    pub fn health_path(&self) -> &str {
        &self.health_path
    }

    pub fn request_path(&self) -> &str {
        &self.request_path
    }

    pub fn shutdown_path(&self) -> &str {
        &self.shutdown_path
    }
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
/// Repository-local activation document generated by `asp install hook`.
pub struct HookActivation {
    pub schema_id: String,
    pub schema_version: String,
    pub schema_authority: String,
    pub protocol_id: String,
    pub protocol_version: String,
    pub project_root: String,
    pub generated_by: ActivationGeneratedBy,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<String>,
    pub rankers: Vec<ActivatedRankerConfig>,
    pub providers: Vec<ActivatedProviderConfig>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ActivatedRankerConfig {
    pub schema_id: String,
    pub ranker_id: String,
    pub capability_id: String,
    pub protocol_version: String,
    pub argv_prefix: Vec<String>,
}

/// Runtime and version that generated a project activation.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ActivationGeneratedBy {
    pub runtime: String,
    pub version: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
/// Repository-local provider activation without provider routes or policies.
///
/// Serialized hook activation DTO. Semantic identities remain typed while
/// transparent serialization preserves the static activation wire representation.
pub struct ActivatedProviderConfig {
    pub manifest_id: String,
    pub manifest_digest: String,
    pub language_id: agent_semantic_config::LanguageId,
    pub provider_id: agent_semantic_config::ProviderId,
    pub search_capabilities: ProviderSearchCapabilities,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub semantic_facts_descriptor: Option<ProviderSemanticFactsDescriptor>,
    pub query_pack_descriptor: ProviderQueryPackDescriptor,
    pub semantic_registry_digest: String,
    pub routes: HookRoutes,
    pub coverage: ActivationCoverage,
}

/// Static provider capability hints used before Runtime Server project resolution.
///
/// These values never assert workspace membership or a resolved source scope.
/// Package roots remain empty during activation; package-manager resolution owns
/// the generation-bound scope published under workspace artifacts.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ActivationCoverage {
    pub package_roots: Vec<String>,
    pub config_files: Vec<String>,
    pub source_extensions: Vec<String>,
}

/// Execution mode used to invoke a provider from ASP.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ProviderExecution {
    /// Provider is executed as an external process.
    #[default]
    ExternalProcess,
    /// Provider is linked into the ASP runtime and dispatched in-process.
    Embedded,
}

impl ProviderExecution {
    /// Stable line-protocol label for provider diagnostics.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::ExternalProcess => "external-process",
            Self::Embedded => "embedded",
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
/// Static provider-owned hook manifest.
///
/// Provider manifest JSON DTO. Semantic identities remain typed while
/// transparent serialization preserves the v1 wire representation.
pub struct ProviderManifest {
    pub(crate) schema_id: String,
    pub(crate) schema_version: String,
    pub(crate) protocol_id: String,
    pub(crate) protocol_version: String,
    pub(crate) manifest_id: String,
    pub(crate) manifest_version: String,
    pub(crate) language_id: agent_semantic_config::LanguageId,
    pub(crate) provider_id: agent_semantic_config::ProviderId,
    pub(crate) namespace: String,
    pub(crate) binary: String,
    pub(crate) runtime_contract: ProviderRuntimeContractDescriptor,
    #[serde(default)]
    pub(crate) execution: ProviderExecution,
    pub(crate) development: ProviderDevelopmentDescriptor,
    pub(crate) search_capabilities: ProviderSearchCapabilities,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) project_resolution: Option<ProviderProjectResolutionDescriptor>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) document_resolution: Option<ProviderDocumentResolutionDescriptor>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) semantic_facts_descriptor: Option<ProviderSemanticFactsDescriptor>,
    pub(crate) query_pack_descriptor: ProviderQueryPackDescriptor,
    pub(crate) policy: HookPolicy,
    pub(crate) route_bindings: crate::protocol::HookRouteBindings,
}

impl ProviderManifest {
    pub fn schema_id(&self) -> &str {
        &self.schema_id
    }

    pub fn schema_version(&self) -> &str {
        &self.schema_version
    }

    pub fn protocol_id(&self) -> &str {
        &self.protocol_id
    }

    pub fn protocol_version(&self) -> &str {
        &self.protocol_version
    }

    pub fn manifest_id(&self) -> &str {
        &self.manifest_id
    }

    pub fn manifest_version(&self) -> &str {
        &self.manifest_version
    }

    pub fn language_id(&self) -> &agent_semantic_config::LanguageId {
        &self.language_id
    }

    pub fn provider_id(&self) -> &agent_semantic_config::ProviderId {
        &self.provider_id
    }

    pub fn namespace(&self) -> &str {
        &self.namespace
    }

    pub fn binary(&self) -> &str {
        &self.binary
    }

    pub fn runtime_contract(&self) -> &ProviderRuntimeContractDescriptor {
        &self.runtime_contract
    }

    pub const fn execution(&self) -> ProviderExecution {
        self.execution
    }

    pub fn development(&self) -> &ProviderDevelopmentDescriptor {
        &self.development
    }

    pub fn search_capabilities(&self) -> &ProviderSearchCapabilities {
        &self.search_capabilities
    }

    pub fn project_resolution(&self) -> Option<&ProviderProjectResolutionDescriptor> {
        self.project_resolution.as_ref()
    }

    pub fn document_resolution(&self) -> Option<&ProviderDocumentResolutionDescriptor> {
        self.document_resolution.as_ref()
    }

    pub fn semantic_facts_descriptor(&self) -> Option<&ProviderSemanticFactsDescriptor> {
        self.semantic_facts_descriptor.as_ref()
    }

    pub fn query_pack_descriptor(&self) -> &ProviderQueryPackDescriptor {
        &self.query_pack_descriptor
    }

    pub fn policy(&self) -> &HookPolicy {
        &self.policy
    }

    pub fn route_bindings(&self) -> &crate::protocol::HookRouteBindings {
        &self.route_bindings
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderDevelopmentDescriptor {
    pub schema_id: String,
    pub schema_version: String,
    pub source_root: String,
    pub build_binding: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_install: Option<String>,
    pub artifact_domain: ProviderDevelopmentArtifactDomain,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ProviderDevelopmentArtifactDomain {
    Checkout,
    StateHomeProviderStaging,
}

/// Provider-owned search surfaces that ASP may delegate instead of approximating.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderSearchCapabilities {
    pub owner_items: bool,
    pub semantic_facts: bool,
    pub dependency_topology: bool,
    pub dependency_topology_metadata: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_snapshot: Option<ProviderSourceSnapshotDescriptor>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderSourceDescriptorId(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderSourceDescriptorVersion(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderSourceSchemaId(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderSourceSnapshotAlgorithm(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderSourceSnapshotAuthority(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderExactSelectorResolution(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderSourceOverlayMode(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderSourceSnapshotDescriptor {
    descriptor_id: ProviderSourceDescriptorId,
    descriptor_version: ProviderSourceDescriptorVersion,
    language_id: agent_semantic_config::LanguageId,
    packet_schema_id: ProviderSourceSchemaId,
    exact_source_packet_schema_id: ProviderSourceSchemaId,
    canonical_item_selector_schema_id: ProviderSourceSchemaId,
    source_snapshot_envelope_schema_id: ProviderSourceSchemaId,
    derived_artifact_evidence_schema_id: ProviderSourceSchemaId,
    algorithm: ProviderSourceSnapshotAlgorithm,
    authority: ProviderSourceSnapshotAuthority,
    exact_selector_resolution: ProviderExactSelectorResolution,
    overlay_mode: ProviderSourceOverlayMode,
}

impl ProviderSourceSnapshotDescriptor {
    pub fn descriptor_id(&self) -> &str {
        &self.descriptor_id.0
    }

    pub fn descriptor_version(&self) -> &str {
        &self.descriptor_version.0
    }

    pub fn language_id(&self) -> &str {
        self.language_id.as_str()
    }

    pub fn packet_schema_id(&self) -> &str {
        &self.packet_schema_id.0
    }

    pub fn exact_source_packet_schema_id(&self) -> &str {
        &self.exact_source_packet_schema_id.0
    }

    pub fn canonical_item_selector_schema_id(&self) -> &str {
        &self.canonical_item_selector_schema_id.0
    }

    pub fn source_snapshot_envelope_schema_id(&self) -> &str {
        &self.source_snapshot_envelope_schema_id.0
    }

    pub fn derived_artifact_evidence_schema_id(&self) -> &str {
        &self.derived_artifact_evidence_schema_id.0
    }

    pub fn algorithm(&self) -> &str {
        &self.algorithm.0
    }

    pub fn authority(&self) -> &str {
        &self.authority.0
    }

    pub fn exact_selector_resolution(&self) -> &str {
        &self.exact_selector_resolution.0
    }

    pub fn overlay_mode(&self) -> &str {
        &self.overlay_mode.0
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderSemanticFactsDescriptor {
    pub descriptor_id: String,
    pub descriptor_version: String,
    pub packet_schema_ids: Vec<String>,
    pub fact_kinds: Vec<String>,
    pub intent_axes: Vec<ProviderSemanticFactsIntentAxis>,
}

/// Repository/worktree discovery belongs to ASP. The provider receives only
/// an already-rebased candidate scope and returns parser-owned project facts.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderProjectResolutionDescriptor {
    pub schema_id: String,
    pub schema_version: String,
    pub capability_id: String,
    /// Workspace-root-relative entry paths matched exactly during provider admission.
    pub entry_markers: Vec<String>,
    #[serde(default)]
    pub source_extensions: Vec<String>,
    pub manifest_kinds: Vec<String>,
    pub lockfile_kinds: Vec<String>,
    pub parser_id: String,
    pub package_graph_schema: String,
    pub project_resolution_schema: String,
}

/// Document parser scope resolved only from Git candidates and registered
/// parser-owned document extensions.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderDocumentResolutionDescriptor {
    pub schema_id: String,
    pub schema_version: String,
    pub capability_id: String,
    pub extensions: Vec<String>,
    pub parser_id: String,
    pub supports_git_candidates: bool,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderSemanticFactAxis(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderSemanticFactTerm(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderSemanticFactsIntentAxis {
    axis: ProviderSemanticFactAxis,
    terms: Vec<ProviderSemanticFactTerm>,
    #[serde(default)]
    roles: Vec<ProviderQueryPackTermRole>,
}

impl ProviderSemanticFactsIntentAxis {
    pub fn axis(&self) -> &str {
        &self.axis.0
    }

    pub fn terms(&self) -> impl Iterator<Item = &str> {
        self.terms.iter().map(|term| term.0.as_str())
    }

    pub fn roles(&self) -> &[ProviderQueryPackTermRole] {
        &self.roles
    }

    /// Return this intent axis with a replaced typed term set.
    #[must_use]
    pub fn with_terms<I, S>(mut self, terms: I) -> Self
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        self.terms = terms
            .into_iter()
            .map(|term| ProviderSemanticFactTerm(term.into()))
            .collect();
        self
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderQueryPackDescriptorId(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderQueryPackDescriptorVersion(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(transparent)]
struct ProviderSemanticFactsDescriptorId(String);

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderQueryPackDescriptor {
    descriptor_id: ProviderQueryPackDescriptorId,
    descriptor_version: ProviderQueryPackDescriptorVersion,
    language_id: agent_semantic_config::LanguageId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    semantic_facts_descriptor_id: Option<ProviderSemanticFactsDescriptorId>,
    #[serde(default)]
    term_role_overrides: Vec<ProviderQueryPackTermRoleOverride>,
    recipes: Vec<ProviderQueryPackRecipe>,
}

impl ProviderQueryPackDescriptor {
    pub fn descriptor_id(&self) -> &str {
        &self.descriptor_id.0
    }

    pub fn descriptor_version(&self) -> &str {
        &self.descriptor_version.0
    }

    pub fn language_id(&self) -> &str {
        self.language_id.as_str()
    }

    pub fn semantic_facts_descriptor_id(&self) -> Option<&str> {
        self.semantic_facts_descriptor_id
            .as_ref()
            .map(|value| value.0.as_str())
    }

    pub fn term_role_overrides(&self) -> &[ProviderQueryPackTermRoleOverride] {
        &self.term_role_overrides
    }

    pub fn recipes(&self) -> &[ProviderQueryPackRecipe] {
        &self.recipes
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ProviderQueryPackTermRole {
    Context,
    Concept,
    Symbol,
    Literal,
    DiagnosticCode,
}

impl ProviderQueryPackTermRole {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Context => "context",
            Self::Concept => "concept",
            Self::Symbol => "symbol",
            Self::Literal => "literal",
            Self::DiagnosticCode => "diagnostic-code",
        }
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderQueryPackTermRoleOverride {
    pub term: String,
    pub role: ProviderQueryPackTermRole,
    #[serde(default)]
    pub case_sensitive: bool,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderQueryPackRecipe {
    pub recipe_id: String,
    pub trigger: ProviderQueryPackTrigger,
    pub clauses: Vec<ProviderQueryPackClause>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderQueryPackTrigger {
    pub terms: Vec<String>,
    pub r#match: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderQueryPackClause {
    pub terms: Vec<String>,
    #[serde(default)]
    pub roles: Vec<ProviderQueryPackTermRole>,
    #[serde(default)]
    pub intent_axes: Vec<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
/// In-memory runtime resolved from activation plus static provider manifests.
pub struct HookRuntime {
    pub project_root: String,
    pub rankers: Vec<ActivatedRankerConfig>,
    pub providers: Vec<ActivatedProvider>,
    #[serde(default)]
    pub policy_providers: Vec<HookProviderProjection>,
}

/// In-memory activated provider selected from a validated manifest.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ActivatedProvider {
    pub manifest_id: String,
    pub manifest_digest: String,
    pub language_id: agent_semantic_config::LanguageId,
    pub provider_id: agent_semantic_config::ProviderId,
    pub namespace: String,
    pub package_roots: Vec<String>,
    pub source_extensions: Vec<String>,
    pub config_files: Vec<String>,
    pub search_capabilities: ProviderSearchCapabilities,
    pub project_resolution: Option<ProviderProjectResolutionDescriptor>,
    pub document_resolution: Option<ProviderDocumentResolutionDescriptor>,
    pub semantic_facts_descriptor: Option<ProviderSemanticFactsDescriptor>,
    pub query_pack_descriptor: ProviderQueryPackDescriptor,
    pub semantic_registry_digest: String,
    pub policy: HookPolicy,
    pub routes: HookRoutes,
}

/// Provider-owned language and routing facts compiled for Hook matching.
///
/// This deliberately excludes execution activation. A document provider or a
/// language provider whose harness is not active still participates in Hook
/// policy without pretending that an executable provider was activated.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct HookProviderProjection {
    pub language_id: agent_semantic_config::LanguageId,
    pub provider_id: agent_semantic_config::ProviderId,
    pub package_roots: Vec<String>,
    pub source_extensions: Vec<String>,
    pub config_files: Vec<String>,
    pub policy: HookPolicy,
    pub owner_route: CommandTemplate,
    pub lexical_route: CommandTemplate,
    pub ingest_route: CommandTemplate,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SourceSelectorKind {
    ExactPath,
    Pattern,
}

#[derive(Clone, Debug)]
pub(crate) struct ProviderSelectorMatch {
    pub provider: HookProviderProjection,
    pub kind: SourceSelectorKind,
}

pub(crate) struct ProviderRoutePathContext {
    pub(crate) selector: String,
    pub(crate) project_root: String,
}
