//! Activation schema DTOs and resolved runtime provider routing models.

use serde::{Deserialize, Serialize};

use crate::protocol::{HookPolicy, HookRoutes};

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
/// Repository-local activation document generated by `asp install hook`.
pub struct HookActivation {
    pub schema_id: String,
    pub schema_version: String,
    pub schema_authority: String,
    pub protocol_id: String,
    pub protocol_version: String,
    pub project_root: String,
    pub generated_by: ActivationGeneratedBy,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<String>,
    pub providers: Vec<ActivatedProviderConfig>,
}

/// Runtime and version that generated a project activation.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ActivationGeneratedBy {
    pub runtime: String,
    pub version: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
/// Repository-local provider activation without provider routes or policies.
///
/// Raw DTO boundary: serialized hook activation keeps primitive transport
/// fields that `resolve_activation` validates against provider manifests.
pub struct ActivatedProviderConfig {
    pub manifest_id: String,
    pub manifest_digest: String,
    pub language_id: String,
    pub provider_id: String,
    pub binary: String,
    #[serde(default)]
    pub execution: ProviderExecution,
    #[serde(default)]
    pub provider_command_prefix: Vec<String>,
    pub execution_command_digest: String,
    pub search_capabilities: ProviderSearchCapabilities,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub semantic_facts_descriptor: Option<ProviderSemanticFactsDescriptor>,
    pub query_pack_descriptor: ProviderQueryPackDescriptor,
    pub semantic_registry_digest: String,
    pub routes: HookRoutes,
    pub coverage: ActivationCoverage,
}

/// Execution mode used to invoke a provider from ASP.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ProviderExecution {
    /// Provider is executed as an external process.
    #[default]
    ExternalProcess,
    /// Provider is linked into the ASP runtime and dispatched in-process.
    Embedded,
}

impl ProviderExecution {
    /// Stable line-protocol label for provider diagnostics.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::ExternalProcess => "external-process",
            Self::Embedded => "embedded",
        }
    }
}

/// Coverage defaults activated from a provider manifest for hook routing.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ActivationCoverage {
    pub package_roots: Vec<String>,
    pub source_roots: Vec<String>,
    pub config_files: Vec<String>,
    pub source_extensions: Vec<String>,
    pub ignored_path_prefixes: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
/// Static provider-owned hook manifest.
///
/// Raw DTO boundary: provider manifest JSON keeps primitive transport fields
/// that `parse_activation` validates before runtime routing.
pub struct ProviderManifest {
    pub schema_id: String,
    pub schema_version: String,
    pub protocol_id: String,
    pub protocol_version: String,
    pub manifest_id: String,
    pub manifest_version: String,
    pub language_id: String,
    pub provider_id: String,
    pub namespace: String,
    pub binary: String,
    #[serde(default)]
    pub execution: ProviderExecution,
    pub source: ManifestSourceDefaults,
    pub search_capabilities: ProviderSearchCapabilities,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub semantic_facts_descriptor: Option<ProviderSemanticFactsDescriptor>,
    pub query_pack_descriptor: ProviderQueryPackDescriptor,
    pub policy: HookPolicy,
    pub route_bindings: crate::protocol::HookRouteBindings,
}

/// Provider-owned search surfaces that ASP may delegate instead of approximating.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderSearchCapabilities {
    pub owner_items: bool,
    pub semantic_facts: bool,
    pub dependency_topology: bool,
    pub dependency_topology_metadata: bool,
    pub workspace_scope: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_snapshot: Option<ProviderSourceSnapshotDescriptor>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderSourceSnapshotDescriptor {
    pub descriptor_id: String,
    pub descriptor_version: String,
    pub language_id: String,
    pub packet_schema_id: String,
    pub exact_source_packet_schema_id: String,
    pub source_snapshot_envelope_schema_id: String,
    pub derived_artifact_evidence_schema_id: String,
    pub algorithm: String,
    pub authority: String,
    pub exact_selector_resolution: String,
    pub overlay_mode: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderSemanticFactsDescriptor {
    pub descriptor_id: String,
    pub descriptor_version: String,
    pub packet_schema_ids: Vec<String>,
    pub fact_kinds: Vec<String>,
    pub intent_axes: Vec<ProviderSemanticFactsIntentAxis>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderSemanticFactsIntentAxis {
    pub axis: String,
    pub terms: Vec<String>,
    #[serde(default)]
    pub roles: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderQueryPackDescriptor {
    pub descriptor_id: String,
    pub descriptor_version: String,
    pub language_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub semantic_facts_descriptor_id: Option<String>,
    #[serde(default)]
    pub term_role_overrides: Vec<ProviderQueryPackTermRoleOverride>,
    pub recipes: Vec<ProviderQueryPackRecipe>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderQueryPackTermRoleOverride {
    pub term: String,
    pub role: String,
    #[serde(default)]
    pub case_sensitive: bool,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderQueryPackRecipe {
    pub recipe_id: String,
    pub trigger: ProviderQueryPackTrigger,
    pub clauses: Vec<ProviderQueryPackClause>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderQueryPackTrigger {
    pub terms: Vec<String>,
    pub r#match: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderQueryPackClause {
    pub terms: Vec<String>,
    #[serde(default)]
    pub roles: Vec<String>,
    #[serde(default)]
    pub intent_axes: Vec<String>,
}

/// Source matching defaults declared by a provider manifest.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ManifestSourceDefaults {
    pub default_extensions: Vec<String>,
    pub default_config_files: Vec<String>,
    pub default_source_roots: Vec<String>,
    pub default_ignored_path_prefixes: Vec<String>,
    #[serde(default)]
    pub default_project_markers: Vec<String>,
    #[serde(default)]
    pub default_dependency_markers: Vec<String>,
}

#[derive(Debug)]
/// In-memory runtime resolved from activation plus static provider manifests.
pub struct HookRuntime {
    pub project_root: String,
    pub providers: Vec<ActivatedProvider>,
}

/// Raw DTO boundary for an activated provider selected from a manifest.
///
/// The string fields preserve manifest and namespace identities exactly as they
/// are serialized for hook runtime activation.
#[derive(Debug)]
pub struct ActivatedProvider {
    pub manifest_id: String,
    pub manifest_digest: String,
    pub language_id: String,
    pub provider_id: String,
    pub binary: String,
    pub execution: ProviderExecution,
    pub provider_command_prefix: Vec<String>,
    pub execution_command_digest: String,
    pub namespace: String,
    pub package_roots: Vec<String>,
    pub source_extensions: Vec<String>,
    pub config_files: Vec<String>,
    pub source_roots: Vec<String>,
    pub ignored_path_prefixes: Vec<String>,
    pub search_capabilities: ProviderSearchCapabilities,
    pub semantic_facts_descriptor: Option<ProviderSemanticFactsDescriptor>,
    pub query_pack_descriptor: ProviderQueryPackDescriptor,
    pub semantic_registry_digest: String,
    pub policy: HookPolicy,
    pub routes: HookRoutes,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SourceSelectorKind {
    ExactPath,
    Pattern,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct ProviderSelectorMatch<'a> {
    pub provider: &'a ActivatedProvider,
    pub kind: SourceSelectorKind,
}

pub(crate) struct ProviderRoutePathContext {
    pub(crate) selector: String,
    pub(crate) project_root: String,
}
