-- SPDX-FileCopyrightText: 2026 tao3k team and Contributors
--
-- SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

import ASPProof.SearchEvidenceDerivation

open ASPProof.SearchEvidenceReflection ASPProof.SearchEvidenceDerivation

def main : IO UInt32 := do
  let row : DisplayRow := ⟨0, occurrenceA, .rg⟩
  let otherCollector : DisplayRow := ⟨1, occurrenceA, .lexical⟩
  let otherBinding : DisplayRow := ⟨0, ⟨storeCall, .firstLiteral, afterBodyEdit⟩, .rg⟩
  let checks : List (String × Bool) := [
    ("same snapshot", unixEdge.snapshot == windowsEdge.snapshot),
    ("disjoint configuration premises", !(unixEdge.allowed.any windowsEdge.allowed.contains)),
    ("positive clause insufficient", fullQuery true true == false),
    ("negative satisfied", fullQuery true false == true),
    ("partial positive retained", certifiedAnswer partialDirectory membership == .supported),
    ("omitted remains unknown", certifiedAnswer partialDirectory storeCall == .unknown),
    ("250 members", (List.range 250).length == 250),
    ("32 displayed", ((List.range 250).take 32).length == 32),
    ("Tokio workspace requests retain distinct semantic keys",
      (⟨1, 10, 100, 1000, 7, 8⟩ : RuntimeWorkspaceRequestKey) !=
        ⟨1, 20, 200, 2000, 7, 9⟩),
    ("duplicates count once", (normalizedSupport [row, row]).length == 1),
    ("two collectors count once", (normalizedSupport [row, otherCollector]).length == 1),
    ("both attributions retained", attribution [row, otherCollector] occurrenceA == [.rg, .lexical]),
    ("changed binding counts separately", (normalizedSupport [row, otherBinding]).length == 2),
    ("alias preserves identity", (rename (· + 1) row).evidence == row.evidence),
    ("cycle returns", cycleNext (cycleNext false) == false),
    ("both cycle edges eligible", eligible false true && eligible true false),
    ("rg-only owner excluded from fused file scope", !fusedScope.contains 1),
    ("Tantivy-only owner excluded from fused file scope", !fusedScope.contains 3),
    ("jointly retrieved owner enters fused file scope", fusedScope.contains 2),
    ("exact native selector owns explicit structural frontier", structuralFrontier fusedScope true automaticStructuralMatches exactStructuralMatches == exactStructuralMatches),
    ("ast-grep match outside file scope is rejected", (structuralFrontier fusedScope true automaticStructuralMatches [⟨1, 11, .astGrepPattern⟩]).isEmpty),
    ("provider projection mints selector inside fused scope", selectorFrom fusedScope candidate validProjection == some .refresh),
    ("syntax projection outside fused scope rejected", selectorFrom fusedScope outsideCandidate { validProjection with ownerPathId := outsideCandidate.pathId } == none),
    ("path alone has no selector", selectorFrom fusedScope candidate unregisteredProjection == none),
    ("stale parser projection rejected", selectorFrom fusedScope candidate staleProjection == none),
    ("bare file URI is not a native syntax anchor", !nativeSyntaxAnchorAdmitted fusedScope 1 bareFileUri),
    ("canonical item selector anchors native syntax", nativeSyntaxAnchorAdmitted fusedScope 1 canonicalItemAnchor),
    ("stale item selector cannot anchor native syntax", !nativeSyntaxAnchorAdmitted fusedScope 1 staleItemAnchor),
    ("native syntax outside fused scope rejected", !nativeSyntaxAnchorAdmitted fusedScope 1 outsideItemAnchor),
    ("frontier core is bounded", frontier100x10.selectedCount == frontier100x10.coreLimit),
    ("frontier reports omitted candidates", frontier100x10.omittedCount == 90),
    ("flat top-k drops owner connector", 1 ∈ [1] && 0 ∉ [1]),
    ("witness closure restores owner connector", 0 ∈ witnessClosure [1] && 1 ∈ witnessClosure [1]),
    ("GQL restatement produces no Ascent output", derivationDelta [1, 2] [1, 2, 1] == []),
    ("new relation survives Ascent delta", derivationDelta [1, 2] [1, 2, 3] == [3]),
    ("naive top-k hides a distinct provider", 2 ∈ denseProviderOrder && 2 ∉ naiveProviderTop3),
    ("diversified frontier retains relevant providers", 1 ∈ diversifiedRelevantProviders && 2 ∈ diversifiedRelevantProviders),
    ("provider existence creates no quota", 3 ∉ diversifiedRelevantProviders)]
    ++ [
    ("Rust native node maps directly to Query", directQueryMapping 1 rustMethodNode == some ⟨.rust, 11, none⟩),
    ("Org native node maps directly to Query", directQueryMapping 1 orgHeadingNode == some ⟨.org, 21, none⟩),
    ("Markdown native node maps directly to Query", directQueryMapping 1 markdownHeadingNode == some ⟨.markdown, 31, none⟩),
    ("JSON node retains selector and jq projection", directQueryMapping 1 jsonObjectWithJqNode == some ⟨.json, 41, some 42⟩),
    ("Python native node maps directly to Query", directQueryMapping 1 pythonFunctionNode == some ⟨.python, 51, none⟩),
    ("TypeScript native node maps directly to Query", directQueryMapping 1 typescriptFunctionNode == some ⟨.typescript, 61, none⟩),
    ("Scheme native node maps directly to Query", directQueryMapping 1 schemeFunctionNode == some ⟨.scheme, 71, none⟩),
    ("Julia native node maps directly to Query", directQueryMapping 1 juliaFunctionNode == some ⟨.julia, 81, none⟩),
    ("Nix native node maps directly to Query", directQueryMapping 1 nixAttributeNode == some ⟨.nix, 91, none⟩),
    ("heterogeneous relations derive one polyglot pipeline", derivePolyglotPipeline polyglotPipelineRelations == some ⟨.rust, .python, .julia, .json, .scheme, .typescript, .org, .markdown, .nix⟩),
    ("missing Scheme validation blocks polyglot pipeline", (derivePolyglotPipeline (polyglotPipelineRelations.erase (.scheme, .json))).isNone),
    ("jq alone cannot mint a selector", directQueryMapping 1 jsonObjectWithoutSelector == none),
    ("source excerpt has no selector authority", sourceExcerptAdmitted 1 unsupportedTextExcerpt && directQueryMapping 1 jsonObjectWithoutSelector == none),
    ("native selector failure cannot downgrade to source excerpt", !sourceExcerptAdmitted 1 failedNativeSelectorExcerpt),
    ("body edit reuses structural topology", structuralTopologyIdentity revisionA == structuralTopologyIdentity bodyEditedRevision),
    ("body edit changes content identity", revisionContentIdentity revisionA != revisionContentIdentity bodyEditedRevision),
    ("structural edit changes topology identity", structuralTopologyIdentity revisionA != structuralTopologyIdentity structurallyEditedRevision),
    ("proposed semantics cannot prove behavior", !factualPremiseEligible .synthesizedProposed),
    ("proposed semantics can open Search frontier", frontierPremiseEligible .synthesizedProposed),
    ("declared topology joins current live evidence", topologyAssistedFactualDerivation 1 currentTopologyEvidence .declared true),
    ("stale semantic topology blocks factual derivation", !topologyAssistedFactualDerivation 1 staleSemanticTopologyEvidence .declared true),
    ("proposed semantics alone cannot become factual", !topologyAssistedFactualDerivation 1 currentTopologyEvidence .synthesizedProposed true),
    ("exact topology library import admitted", (loadTopologyLibrary 1 ⟨7, 17, 27⟩ admittedTopologyLibrary).isSome),
    ("semantic identity drift rejects library", (loadTopologyLibrary 1 ⟨7, 17, 27⟩ staleTopologyLibrary).isNone),
    ("proposed claim excluded from factual closure", factualTopologyClaims { admittedTopologyLibrary with semanticClaims := [.declared, .synthesizedProposed] } == [.declared]),
    ("live evidence is staged before topology inference", stageTopologyEvaluationInput admittedTopologyLibrary [102] == [100, 101, 102]),
    ("recursive closure derives new knowledge", decide ((.refreshRegistry, .commitReceipt) ∈ closureWithin 1 reasoningEdges)),
    ("new closure knowledge was absent from EDB", decide ((.refreshRegistry, .commitReceipt) ∉ reasoningEdges)),
    ("GQL facts join into documented path", decide ((.refreshRegistry, .publicationHeading) ∈ deriveDocumentedPaths (closureWithin 1 reasoningEdges) documentEdges)),
    ("CALLS EXPLAINS EMITS join into publication path", decide ((⟨.refreshRegistry, .publishArtifact, .publicationHeading, .commitReceipt⟩ : PublicationPathFact) ∈ publicationPaths)),
    ("one Query Playbook receives one materialization set", publicationMaterializationSet publicationPaths == ⟨[.publishArtifact, .commitReceipt]⟩),
    ("frontier proposal cannot be a premise", !admissibleAsPremise (.frontier .publishArtifact 7)),
    ("skipped delta is rejected", !deltaComplete [1, 2] [1, 2, 3] []),
    ("complete delta is admitted", deltaComplete [1, 2] [1, 2, 3] [3]),
    ("default projection hides internal Ascent", !defaultAgentProjectionExposesAscentSource),
    ("GQL retains a direct parser edge", decide (⟨(.refreshRegistry, .publishArtifact), .parserDirect, none, none⟩ ∈ settledPublicationGraph)),
    ("GQL marks a novel edge derived", decide (⟨(.refreshRegistry, .commitReceipt), .derived, some 27, some 42⟩ ∈ settledPublicationGraph)),
    ("model summary retains premises", proposedPublicationSummary.premises == [40, 42]),
    ("proposed summary cannot prove behavior", !annotationCanProveBehavior 1 proposedPublicationSummary),
    ("accepted summary can join its current binding", annotationCanProveBehavior 1 acceptedPublicationSummary),
    ("accepted summary is rejected after binding drift", !annotationCanProveBehavior 2 acceptedPublicationSummary),
    ("partial coverage remains unknown", classifyRelation .boundedPartial false == .unresolved),
    ("complete coverage can certify missing", classifyRelation .certifiedComplete false == .certifiedMissing),
    ("seed-relative path depth validates", reachedAtValid publicationReachedAt),
    ("decision core closes transitive proof dependencies", dependencyClosure 2 transitiveProofDependencies [3] == [3, 2, 1]),
    ("generation replacement retracts deletion", applyGenerationDelta 1 [1, 2] removePublishedEdge == some [1]),
    ("fuel exhaustion alone is not fixed point", !fixedPoint reasoningEdges reasoningEdges),
    ("bounded finite closure reaches fixed point", fixedPoint reasoningEdges (closureWithin 2 reasoningEdges)),
    ("Search settlement binds the exact reusable topology generation", settlementBoundToLibrary projectTopologyIdentity exactSearchTopologyIdentity),
    ("cross-generation topology replay is rejected", !settlementBoundToLibrary projectTopologyIdentity replayedSearchTopologyIdentity),
    ("accepted prose without an admission receipt is not factual", !admittedAnnotationCanProveBehavior 1 ⟨7, acceptedPublicationSummary, none⟩),
    ("accepted prose with exact binding and receipt is factual", admittedAnnotationCanProveBehavior 1 ⟨7, acceptedPublicationSummary, some ⟨1, 7, 51⟩⟩),
    ("foreign semantic admission receipt is rejected", !admittedAnnotationCanProveBehavior 1 ⟨7, acceptedPublicationSummary, some ⟨2, 8, 51⟩⟩),
    ("self-declared digest equality is not rebuild proof", !fromScratchEquivalenceAdmitted 11 17 14 13 [] none),
    ("external rebuild receipt binds generation and library", fromScratchEquivalenceAdmitted 11 17 14 13 [⟨11, 17, 14, 13, 61⟩] (some ⟨11, 17, 14, 13, 61⟩)),
    ("stale rebuild receipt is rejected", !fromScratchEquivalenceAdmitted 11 17 14 13 [⟨11, 17, 12, 13, 61⟩] (some ⟨11, 17, 12, 13, 61⟩)),
    ("settled direct relation retains binding and witnesses", decide (⟨(.refreshRegistry, .publishArtifact), .parserDirect, 1, [40, 42], none, none⟩ ∈ boundPublicationGraph)),
    ("settled derived relation retains inference proof authority", decide (⟨(.refreshRegistry, .commitReceipt), .derived, 1, [40, 42], some 27, some 43⟩ ∈ boundPublicationGraph)),
    ("base deletion invalidates every derived descendant", invalidationClosure 2 transitiveDerivedFacts [2] == [2, 3, 4]),
    ("invalidated derived descendants cannot remain materialized", retainedDerivedFacts transitiveDerivedFacts (invalidationClosure 2 transitiveDerivedFacts [2]) == []),
    ("budget exhaustion is not an inference settlement", !inferenceReceiptAdmitted 11 17 [⟨11, 17, reasoningEdges, closureStep reasoningEdges reasoningEdges, .budgetExhausted, 71⟩] ⟨11, 17, reasoningEdges, closureStep reasoningEdges reasoningEdges, .budgetExhausted, 71⟩),
    ("stable fixed point has an admitted terminal receipt", let closure := closureWithin 2 reasoningEdges; inferenceReceiptAdmitted 11 17 [⟨11, 17, closure, closureStep reasoningEdges closure, .fixedPoint, 71⟩] ⟨11, 17, closure, closureStep reasoningEdges closure, .fixedPoint, 71⟩),
    ("materialization set is sorted and selector-available", materializationSetAdmitted [10, 20, 30] [10, 30]),
    ("duplicate materialization is rejected", !materializationSetAdmitted [10, 20, 30] [10, 10]),
    ("unavailable materialization is rejected", !materializationSetAdmitted [10, 20, 30] [10, 40]),
    ("smallest Runtime-admitted selector set is directly queryable", queryPlaybookRequestAdmitted currentRuntimeBinding 61 51 [10, 20, 30] ⟨101, 1, 2, currentRuntimeBinding, 61, 51, [10], 7⟩),
    ("selectors learned across searches can form one Query", queryPlaybookRequestAdmitted currentRuntimeBinding 61 51 [10, 20, 30] ⟨101, 1, 2, currentRuntimeBinding, 61, 51, [10, 30], 7⟩),
    ("Runtime binding replay is rejected before Query materialization", !queryPlaybookRequestAdmitted currentRuntimeBinding 61 51 [10, 20, 30] ⟨101, 1, 2, { currentRuntimeBinding with runtimeArtifact := 99 }, 61, 51, [10], 7⟩),
    ("unavailable selector is rejected before Query materialization", !queryPlaybookRequestAdmitted currentRuntimeBinding 61 51 [10, 20, 30] ⟨101, 1, 2, currentRuntimeBinding, 61, 51, [10, 40], 7⟩),
    ("foreign outer Runtime bundle is rejected before Query materialization", !queryPlaybookRequestAdmitted currentRuntimeBinding 61 51 [10, 20, 30] ⟨101, 1, 2, currentRuntimeBinding, 62, 51, [10], 7⟩),
    ("foreign execution publication is rejected before Query materialization", !queryPlaybookRequestAdmitted currentRuntimeBinding 61 51 [10, 20, 30] ⟨101, 1, 2, currentRuntimeBinding, 61, 52, [10], 7⟩),
    ("exact bound provider projection is admitted", boundProviderRegisterProjectionAdmitted [1, 2] [1, 2] false),
    ("persisted provider cannot supplement bound projection", !boundProviderRegisterProjectionAdmitted [1, 2] [1, 2, 3] false),
    ("live provider mutation cannot preserve bound authority", !boundProviderRegisterProjectionAdmitted [1, 2] [1, 2] true)]
    ++ [
    ("equal inner Runtime binding cannot authorize a foreign outer bundle", !runtimeWorkspaceExecutionPublicationAdmitted 1 31 41 ⟨4, none, 31⟩ currentRuntimeBinding 62 51 currentWorkspaceExecutionPublication),
    ("client timing is enriched with the server publication", settleClientSearchTiming 7 8 currentWorkspaceExecutionPublication ⟨7, 8, [10, 20, 30]⟩ == some ⟨7, 8, currentWorkspaceExecutionPublication⟩),
    ("foreign client request receives no Runtime telemetry identity", (settleClientSearchTiming 7 8 currentWorkspaceExecutionPublication ⟨7, 9, [10, 20, 30]⟩).isNone),
    ("client timing values cannot select Runtime identity", (settleClientSearchTiming 7 8 currentWorkspaceExecutionPublication ⟨7, 8, [1]⟩).map SettledSearchTelemetryIdentity.publication == (settleClientSearchTiming 7 8 currentWorkspaceExecutionPublication ⟨7, 8, [999]⟩).map SettledSearchTelemetryIdentity.publication),
    ("exact Host workspace initialization binding is admitted", hostWorkspaceInitializationBindingAdmitted currentProjectWorkspace currentHostWorkspaceInitialization currentHostWorkspaceInitialization),
    ("Client workspace identity cannot replace Host worktree identity", !hostWorkspaceInitializationBindingAdmitted currentProjectWorkspace currentHostWorkspaceInitialization { currentHostWorkspaceInitialization with worktreeInstance := 99 })]
  let failed := checks.filter (fun check => !check.2)
  for check in failed do
    IO.eprintln s!"FAIL: {check.1}"
  IO.println s!"SearchEvidenceDerivation: {checks.length - failed.length}/{checks.length} checks passed"
  return if failed.isEmpty then 0 else 1
