# SPDX-FileCopyrightText: 2026 tao3k team and Contributors
#
# SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-only

[package]
name = "dep-seed-api-selector-public-api"
license.workspace = true
version = "0.1.0"
edition = "2024"

[dependencies]
rust-lang-project-harness = { path = "rust-lang-project-harness" }
